/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.BusConditionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusCondition extends TableImpl<BusConditionRecord> {

    private static final long serialVersionUID = 41131807;

    /**
     * The reference instance of <code>public.bus_condition</code>
     */
    public static final BusCondition BUS_CONDITION = new BusCondition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BusConditionRecord> getRecordType() {
        return BusConditionRecord.class;
    }

    /**
     * The column <code>public.bus_condition.id</code>.
     */
    public final TableField<BusConditionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('bus_condition_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.bus_condition.name</code>.
     */
    public final TableField<BusConditionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.bus_condition.removed</code>.
     */
    public final TableField<BusConditionRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.bus_condition</code> table reference
     */
    public BusCondition() {
        this(DSL.name("bus_condition"), null);
    }

    /**
     * Create an aliased <code>public.bus_condition</code> table reference
     */
    public BusCondition(String alias) {
        this(DSL.name(alias), BUS_CONDITION);
    }

    /**
     * Create an aliased <code>public.bus_condition</code> table reference
     */
    public BusCondition(Name alias) {
        this(alias, BUS_CONDITION);
    }

    private BusCondition(Name alias, Table<BusConditionRecord> aliased) {
        this(alias, aliased, null);
    }

    private BusCondition(Name alias, Table<BusConditionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BusCondition(Table<O> child, ForeignKey<O, BusConditionRecord> key) {
        super(child, key, BUS_CONDITION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_BUS_CONDITION_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BusConditionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BUS_CONDITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BusConditionRecord> getPrimaryKey() {
        return Keys.PK_BUS_CONDITION_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BusConditionRecord>> getKeys() {
        return Arrays.<UniqueKey<BusConditionRecord>>asList(Keys.PK_BUS_CONDITION_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusCondition as(String alias) {
        return new BusCondition(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusCondition as(Name alias) {
        return new BusCondition(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BusCondition rename(String name) {
        return new BusCondition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BusCondition rename(Name name) {
        return new BusCondition(name, null);
    }
}
