/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.time.OffsetTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.DepartureMomentsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartureMoments extends TableImpl<DepartureMomentsRecord> {

    private static final long serialVersionUID = -1510349726;

    /**
     * The reference instance of <code>public.departure_moments</code>
     */
    public static final DepartureMoments DEPARTURE_MOMENTS = new DepartureMoments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartureMomentsRecord> getRecordType() {
        return DepartureMomentsRecord.class;
    }

    /**
     * The column <code>public.departure_moments.id</code>.
     */
    public final TableField<DepartureMomentsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('departure_moments_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.departure_moments.departure_list_id</code>.
     */
    public final TableField<DepartureMomentsRecord, Short> DEPARTURE_LIST_ID = createField("departure_list_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.departure_moments.order</code>.
     */
    public final TableField<DepartureMomentsRecord, Short> ORDER = createField("order", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.departure_moments.start_time</code>.
     */
    public final TableField<DepartureMomentsRecord, OffsetTime> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMEWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>public.departure_moments.removed</code>.
     */
    public final TableField<DepartureMomentsRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.departure_moments</code> table reference
     */
    public DepartureMoments() {
        this(DSL.name("departure_moments"), null);
    }

    /**
     * Create an aliased <code>public.departure_moments</code> table reference
     */
    public DepartureMoments(String alias) {
        this(DSL.name(alias), DEPARTURE_MOMENTS);
    }

    /**
     * Create an aliased <code>public.departure_moments</code> table reference
     */
    public DepartureMoments(Name alias) {
        this(alias, DEPARTURE_MOMENTS);
    }

    private DepartureMoments(Name alias, Table<DepartureMomentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DepartureMoments(Name alias, Table<DepartureMomentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DepartureMoments(Table<O> child, ForeignKey<O, DepartureMomentsRecord> key) {
        super(child, key, DEPARTURE_MOMENTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DEPARTURE_MOMENTS_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DepartureMomentsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DEPARTURE_MOMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DepartureMomentsRecord> getPrimaryKey() {
        return Keys.PK_DEPARTURE_MOMENTS_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DepartureMomentsRecord>> getKeys() {
        return Arrays.<UniqueKey<DepartureMomentsRecord>>asList(Keys.PK_DEPARTURE_MOMENTS_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DepartureMomentsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DepartureMomentsRecord, ?>>asList(Keys.DEPARTURE_MOMENTS__FK_DEPARTURE_MOMENTS_TBL_DEPARTURE_LIST_ID);
    }

    public DepartureList departureList() {
        return new DepartureList(this, Keys.DEPARTURE_MOMENTS__FK_DEPARTURE_MOMENTS_TBL_DEPARTURE_LIST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartureMoments as(String alias) {
        return new DepartureMoments(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartureMoments as(Name alias) {
        return new DepartureMoments(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartureMoments rename(String name) {
        return new DepartureMoments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartureMoments rename(Name name) {
        return new DepartureMoments(name, null);
    }
}
