/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.sql.Date;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.DriverScheduleSnapshotRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverScheduleSnapshot extends TableImpl<DriverScheduleSnapshotRecord> {

    private static final long serialVersionUID = -60491454;

    /**
     * The reference instance of <code>public.driver_schedule_snapshot</code>
     */
    public static final DriverScheduleSnapshot DRIVER_SCHEDULE_SNAPSHOT = new DriverScheduleSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DriverScheduleSnapshotRecord> getRecordType() {
        return DriverScheduleSnapshotRecord.class;
    }

    /**
     * The column <code>public.driver_schedule_snapshot.employee_id</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, Short> EMPLOYEE_ID = createField("employee_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.driver_schedule_snapshot.date</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.driver_schedule_snapshot.shift_type_id</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, Short> SHIFT_TYPE_ID = createField("shift_type_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.driver_schedule_snapshot.created_at</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, OffsetDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>public.driver_schedule_snapshot.ended_at</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, OffsetDateTime> ENDED_AT = createField("ended_at", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>public.driver_schedule_snapshot.removed</code>.
     */
    public final TableField<DriverScheduleSnapshotRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.driver_schedule_snapshot</code> table reference
     */
    public DriverScheduleSnapshot() {
        this(DSL.name("driver_schedule_snapshot"), null);
    }

    /**
     * Create an aliased <code>public.driver_schedule_snapshot</code> table reference
     */
    public DriverScheduleSnapshot(String alias) {
        this(DSL.name(alias), DRIVER_SCHEDULE_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.driver_schedule_snapshot</code> table reference
     */
    public DriverScheduleSnapshot(Name alias) {
        this(alias, DRIVER_SCHEDULE_SNAPSHOT);
    }

    private DriverScheduleSnapshot(Name alias, Table<DriverScheduleSnapshotRecord> aliased) {
        this(alias, aliased, null);
    }

    private DriverScheduleSnapshot(Name alias, Table<DriverScheduleSnapshotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DriverScheduleSnapshot(Table<O> child, ForeignKey<O, DriverScheduleSnapshotRecord> key) {
        super(child, key, DRIVER_SCHEDULE_SNAPSHOT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DRIVER_SCHEDULE_SNAPSHOT_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DriverScheduleSnapshotRecord> getPrimaryKey() {
        return Keys.PK_DRIVER_SCHEDULE_SNAPSHOT_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DriverScheduleSnapshotRecord>> getKeys() {
        return Arrays.<UniqueKey<DriverScheduleSnapshotRecord>>asList(Keys.PK_DRIVER_SCHEDULE_SNAPSHOT_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DriverScheduleSnapshotRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DriverScheduleSnapshotRecord, ?>>asList(Keys.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_EMPLOYEE_ID_FK, Keys.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID);
    }

    public Driver driver() {
        return new Driver(this, Keys.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_EMPLOYEE_ID_FK);
    }

    public ShiftType shiftType() {
        return new ShiftType(this, Keys.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshot as(String alias) {
        return new DriverScheduleSnapshot(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshot as(Name alias) {
        return new DriverScheduleSnapshot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverScheduleSnapshot rename(String name) {
        return new DriverScheduleSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverScheduleSnapshot rename(Name name) {
        return new DriverScheduleSnapshot(name, null);
    }
}
