/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.DriverGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverGroup extends TableImpl<DriverGroupRecord> {

    private static final long serialVersionUID = -124377751;

    /**
     * The reference instance of <code>public.driver_group</code>
     */
    public static final DriverGroup DRIVER_GROUP = new DriverGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DriverGroupRecord> getRecordType() {
        return DriverGroupRecord.class;
    }

    /**
     * The column <code>public.driver_group.id</code>.
     */
    public final TableField<DriverGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('driver_group_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.driver_group.description</code>.
     */
    public final TableField<DriverGroupRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.driver_group.brigade_id</code>.
     */
    public final TableField<DriverGroupRecord, Short> BRIGADE_ID = createField("brigade_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.driver_group.removed</code>.
     */
    public final TableField<DriverGroupRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.driver_group</code> table reference
     */
    public DriverGroup() {
        this(DSL.name("driver_group"), null);
    }

    /**
     * Create an aliased <code>public.driver_group</code> table reference
     */
    public DriverGroup(String alias) {
        this(DSL.name(alias), DRIVER_GROUP);
    }

    /**
     * Create an aliased <code>public.driver_group</code> table reference
     */
    public DriverGroup(Name alias) {
        this(alias, DRIVER_GROUP);
    }

    private DriverGroup(Name alias, Table<DriverGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private DriverGroup(Name alias, Table<DriverGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DriverGroup(Table<O> child, ForeignKey<O, DriverGroupRecord> key) {
        super(child, key, DRIVER_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DRIVER_GROUP_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DriverGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DRIVER_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DriverGroupRecord> getPrimaryKey() {
        return Keys.PK_DRIVER_GROUP_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DriverGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<DriverGroupRecord>>asList(Keys.PK_DRIVER_GROUP_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DriverGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DriverGroupRecord, ?>>asList(Keys.DRIVER_GROUP__FK_DRIVER_GROUP_TBL_BRIGADE_ID);
    }

    public DriverBrigade driverBrigade() {
        return new DriverBrigade(this, Keys.DRIVER_GROUP__FK_DRIVER_GROUP_TBL_BRIGADE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverGroup as(String alias) {
        return new DriverGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverGroup as(Name alias) {
        return new DriverGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverGroup rename(String name) {
        return new DriverGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverGroup rename(Name name) {
        return new DriverGroup(name, null);
    }
}
