/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.DriverBrigadeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverBrigade extends TableImpl<DriverBrigadeRecord> {

    private static final long serialVersionUID = 656706893;

    /**
     * The reference instance of <code>public.driver_brigade</code>
     */
    public static final DriverBrigade DRIVER_BRIGADE = new DriverBrigade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DriverBrigadeRecord> getRecordType() {
        return DriverBrigadeRecord.class;
    }

    /**
     * The column <code>public.driver_brigade.id</code>.
     */
    public final TableField<DriverBrigadeRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('driver_brigade_id_seq'::regclass)", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.driver_brigade.description</code>.
     */
    public final TableField<DriverBrigadeRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.driver_brigade.removed</code>.
     */
    public final TableField<DriverBrigadeRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.driver_brigade</code> table reference
     */
    public DriverBrigade() {
        this(DSL.name("driver_brigade"), null);
    }

    /**
     * Create an aliased <code>public.driver_brigade</code> table reference
     */
    public DriverBrigade(String alias) {
        this(DSL.name(alias), DRIVER_BRIGADE);
    }

    /**
     * Create an aliased <code>public.driver_brigade</code> table reference
     */
    public DriverBrigade(Name alias) {
        this(alias, DRIVER_BRIGADE);
    }

    private DriverBrigade(Name alias, Table<DriverBrigadeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DriverBrigade(Name alias, Table<DriverBrigadeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DriverBrigade(Table<O> child, ForeignKey<O, DriverBrigadeRecord> key) {
        super(child, key, DRIVER_BRIGADE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DRIVER_BRIGADE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DriverBrigadeRecord, Short> getIdentity() {
        return Keys.IDENTITY_DRIVER_BRIGADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DriverBrigadeRecord> getPrimaryKey() {
        return Keys.PK_DRIVER_BRIGADE_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DriverBrigadeRecord>> getKeys() {
        return Arrays.<UniqueKey<DriverBrigadeRecord>>asList(Keys.PK_DRIVER_BRIGADE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverBrigade as(String alias) {
        return new DriverBrigade(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverBrigade as(Name alias) {
        return new DriverBrigade(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverBrigade rename(String name) {
        return new DriverBrigade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DriverBrigade rename(Name name) {
        return new DriverBrigade(name, null);
    }
}
