/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.sql.Date;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.GenerationInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenerationInfo extends TableImpl<GenerationInfoRecord> {

    private static final long serialVersionUID = -1012533705;

    /**
     * The reference instance of <code>public.generation_info</code>
     */
    public static final GenerationInfo GENERATION_INFO = new GenerationInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenerationInfoRecord> getRecordType() {
        return GenerationInfoRecord.class;
    }

    /**
     * The column <code>public.generation_info.date</code>.
     */
    public final TableField<GenerationInfoRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.generation_info.status_id</code>.
     */
    public final TableField<GenerationInfoRecord, Short> STATUS_ID = createField("status_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.generation_info.created_at</code>.
     */
    public final TableField<GenerationInfoRecord, OffsetDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>public.generation_info.removed</code>.
     */
    public final TableField<GenerationInfoRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>public.generation_info</code> table reference
     */
    public GenerationInfo() {
        this(DSL.name("generation_info"), null);
    }

    /**
     * Create an aliased <code>public.generation_info</code> table reference
     */
    public GenerationInfo(String alias) {
        this(DSL.name(alias), GENERATION_INFO);
    }

    /**
     * Create an aliased <code>public.generation_info</code> table reference
     */
    public GenerationInfo(Name alias) {
        this(alias, GENERATION_INFO);
    }

    private GenerationInfo(Name alias, Table<GenerationInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private GenerationInfo(Name alias, Table<GenerationInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GenerationInfo(Table<O> child, ForeignKey<O, GenerationInfoRecord> key) {
        super(child, key, GENERATION_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_GENERATION_INFO_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GenerationInfoRecord> getPrimaryKey() {
        return Keys.PK_GENERATION_INFO_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GenerationInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<GenerationInfoRecord>>asList(Keys.PK_GENERATION_INFO_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationInfo as(String alias) {
        return new GenerationInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationInfo as(Name alias) {
        return new GenerationInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GenerationInfo rename(String name) {
        return new GenerationInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GenerationInfo rename(Name name) {
        return new GenerationInfo(name, null);
    }
}
