/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.RbBusMakeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RbBusMake extends TableImpl<RbBusMakeRecord> {

    private static final long serialVersionUID = -2008164278;

    /**
     * The reference instance of <code>public.rb_bus_make</code>
     */
    public static final RbBusMake RB_BUS_MAKE = new RbBusMake();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RbBusMakeRecord> getRecordType() {
        return RbBusMakeRecord.class;
    }

    /**
     * The column <code>public.rb_bus_make.id</code>.
     */
    public final TableField<RbBusMakeRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('rb_bus_make_id_seq'::regclass)", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.rb_bus_make.name</code>.
     */
    public final TableField<RbBusMakeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.rb_bus_make.removed</code>.
     */
    public final TableField<RbBusMakeRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.rb_bus_make</code> table reference
     */
    public RbBusMake() {
        this(DSL.name("rb_bus_make"), null);
    }

    /**
     * Create an aliased <code>public.rb_bus_make</code> table reference
     */
    public RbBusMake(String alias) {
        this(DSL.name(alias), RB_BUS_MAKE);
    }

    /**
     * Create an aliased <code>public.rb_bus_make</code> table reference
     */
    public RbBusMake(Name alias) {
        this(alias, RB_BUS_MAKE);
    }

    private RbBusMake(Name alias, Table<RbBusMakeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RbBusMake(Name alias, Table<RbBusMakeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RbBusMake(Table<O> child, ForeignKey<O, RbBusMakeRecord> key) {
        super(child, key, RB_BUS_MAKE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_RB_BUS_MAKE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RbBusMakeRecord, Short> getIdentity() {
        return Keys.IDENTITY_RB_BUS_MAKE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RbBusMakeRecord> getPrimaryKey() {
        return Keys.PK_RB_BUS_MAKE_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RbBusMakeRecord>> getKeys() {
        return Arrays.<UniqueKey<RbBusMakeRecord>>asList(Keys.PK_RB_BUS_MAKE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusMake as(String alias) {
        return new RbBusMake(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusMake as(Name alias) {
        return new RbBusMake(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RbBusMake rename(String name) {
        return new RbBusMake(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RbBusMake rename(Name name) {
        return new RbBusMake(name, null);
    }
}
