/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.RbEmployeeScheduleTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RbEmployeeScheduleType extends TableImpl<RbEmployeeScheduleTypeRecord> {

    private static final long serialVersionUID = 1145903393;

    /**
     * The reference instance of <code>public.rb_employee_schedule_type</code>
     */
    public static final RbEmployeeScheduleType RB_EMPLOYEE_SCHEDULE_TYPE = new RbEmployeeScheduleType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RbEmployeeScheduleTypeRecord> getRecordType() {
        return RbEmployeeScheduleTypeRecord.class;
    }

    /**
     * The column <code>public.rb_employee_schedule_type.id</code>.
     */
    public final TableField<RbEmployeeScheduleTypeRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('rb_employee_schedule_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.rb_employee_schedule_type.type_description</code>.
     */
    public final TableField<RbEmployeeScheduleTypeRecord, String> TYPE_DESCRIPTION = createField("type_description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.rb_employee_schedule_type.removed</code>.
     */
    public final TableField<RbEmployeeScheduleTypeRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.rb_employee_schedule_type</code> table reference
     */
    public RbEmployeeScheduleType() {
        this(DSL.name("rb_employee_schedule_type"), null);
    }

    /**
     * Create an aliased <code>public.rb_employee_schedule_type</code> table reference
     */
    public RbEmployeeScheduleType(String alias) {
        this(DSL.name(alias), RB_EMPLOYEE_SCHEDULE_TYPE);
    }

    /**
     * Create an aliased <code>public.rb_employee_schedule_type</code> table reference
     */
    public RbEmployeeScheduleType(Name alias) {
        this(alias, RB_EMPLOYEE_SCHEDULE_TYPE);
    }

    private RbEmployeeScheduleType(Name alias, Table<RbEmployeeScheduleTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RbEmployeeScheduleType(Name alias, Table<RbEmployeeScheduleTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RbEmployeeScheduleType(Table<O> child, ForeignKey<O, RbEmployeeScheduleTypeRecord> key) {
        super(child, key, RB_EMPLOYEE_SCHEDULE_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RbEmployeeScheduleTypeRecord, Short> getIdentity() {
        return Keys.IDENTITY_RB_EMPLOYEE_SCHEDULE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RbEmployeeScheduleTypeRecord> getPrimaryKey() {
        return Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RbEmployeeScheduleTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<RbEmployeeScheduleTypeRecord>>asList(Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbEmployeeScheduleType as(String alias) {
        return new RbEmployeeScheduleType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbEmployeeScheduleType as(Name alias) {
        return new RbEmployeeScheduleType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RbEmployeeScheduleType rename(String name) {
        return new RbEmployeeScheduleType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RbEmployeeScheduleType rename(Name name) {
        return new RbEmployeeScheduleType(name, null);
    }
}
