/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.RbFuelTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RbFuelType extends TableImpl<RbFuelTypeRecord> {

    private static final long serialVersionUID = 1535512642;

    /**
     * The reference instance of <code>public.rb_fuel_type</code>
     */
    public static final RbFuelType RB_FUEL_TYPE = new RbFuelType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RbFuelTypeRecord> getRecordType() {
        return RbFuelTypeRecord.class;
    }

    /**
     * The column <code>public.rb_fuel_type.id</code>.
     */
    public final TableField<RbFuelTypeRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('rb_fuel_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.rb_fuel_type.fuel_mark</code>.
     */
    public final TableField<RbFuelTypeRecord, String> FUEL_MARK = createField("fuel_mark", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.rb_fuel_type.removed</code>.
     */
    public final TableField<RbFuelTypeRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.rb_fuel_type</code> table reference
     */
    public RbFuelType() {
        this(DSL.name("rb_fuel_type"), null);
    }

    /**
     * Create an aliased <code>public.rb_fuel_type</code> table reference
     */
    public RbFuelType(String alias) {
        this(DSL.name(alias), RB_FUEL_TYPE);
    }

    /**
     * Create an aliased <code>public.rb_fuel_type</code> table reference
     */
    public RbFuelType(Name alias) {
        this(alias, RB_FUEL_TYPE);
    }

    private RbFuelType(Name alias, Table<RbFuelTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private RbFuelType(Name alias, Table<RbFuelTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RbFuelType(Table<O> child, ForeignKey<O, RbFuelTypeRecord> key) {
        super(child, key, RB_FUEL_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PL_RB_FUEL_TYPE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RbFuelTypeRecord, Short> getIdentity() {
        return Keys.IDENTITY_RB_FUEL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RbFuelTypeRecord> getPrimaryKey() {
        return Keys.PL_RB_FUEL_TYPE_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RbFuelTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<RbFuelTypeRecord>>asList(Keys.PL_RB_FUEL_TYPE_TBL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbFuelType as(String alias) {
        return new RbFuelType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbFuelType as(Name alias) {
        return new RbFuelType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RbFuelType rename(String name) {
        return new RbFuelType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RbFuelType rename(Name name) {
        return new RbFuelType(name, null);
    }
}
