/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.bus.postgres.Indexes;
import ru.smartsarov.bus.postgres.Keys;
import ru.smartsarov.bus.postgres.Public;
import ru.smartsarov.bus.postgres.tables.records.RouteScheduleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteSchedule extends TableImpl<RouteScheduleRecord> {

    private static final long serialVersionUID = 526417491;

    /**
     * The reference instance of <code>public.route_schedule</code>
     */
    public static final RouteSchedule ROUTE_SCHEDULE = new RouteSchedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RouteScheduleRecord> getRecordType() {
        return RouteScheduleRecord.class;
    }

    /**
     * The column <code>public.route_schedule.route_id</code>.
     */
    public final TableField<RouteScheduleRecord, Short> ROUTE_ID = createField("route_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.route_schedule.departure_list_id</code>.
     */
    public final TableField<RouteScheduleRecord, Short> DEPARTURE_LIST_ID = createField("departure_list_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.route_schedule.removed</code>.
     */
    public final TableField<RouteScheduleRecord, Short> REMOVED = createField("removed", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>public.route_schedule</code> table reference
     */
    public RouteSchedule() {
        this(DSL.name("route_schedule"), null);
    }

    /**
     * Create an aliased <code>public.route_schedule</code> table reference
     */
    public RouteSchedule(String alias) {
        this(DSL.name(alias), ROUTE_SCHEDULE);
    }

    /**
     * Create an aliased <code>public.route_schedule</code> table reference
     */
    public RouteSchedule(Name alias) {
        this(alias, ROUTE_SCHEDULE);
    }

    private RouteSchedule(Name alias, Table<RouteScheduleRecord> aliased) {
        this(alias, aliased, null);
    }

    private RouteSchedule(Name alias, Table<RouteScheduleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RouteSchedule(Table<O> child, ForeignKey<O, RouteScheduleRecord> key) {
        super(child, key, ROUTE_SCHEDULE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_ROUTE_SCHEDULE_TBL, Indexes.UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RouteScheduleRecord> getPrimaryKey() {
        return Keys.PK_ROUTE_SCHEDULE_TBL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RouteScheduleRecord>> getKeys() {
        return Arrays.<UniqueKey<RouteScheduleRecord>>asList(Keys.PK_ROUTE_SCHEDULE_TBL, Keys.UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RouteScheduleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RouteScheduleRecord, ?>>asList(Keys.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_ROUTE_ID, Keys.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID);
    }

    public Route route() {
        return new Route(this, Keys.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_ROUTE_ID);
    }

    public DepartureList departureList() {
        return new DepartureList(this, Keys.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteSchedule as(String alias) {
        return new RouteSchedule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteSchedule as(Name alias) {
        return new RouteSchedule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteSchedule rename(String name) {
        return new RouteSchedule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteSchedule rename(Name name) {
        return new RouteSchedule(name, null);
    }
}
