/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.smartsarov.bus.postgres.tables.Bus;
import ru.smartsarov.bus.postgres.tables.BusInfo;
import ru.smartsarov.bus.postgres.tables.BusSnapshot;
import ru.smartsarov.bus.postgres.tables.BusStopList;
import ru.smartsarov.bus.postgres.tables.BusStops;
import ru.smartsarov.bus.postgres.tables.CondEmployeeInfo;
import ru.smartsarov.bus.postgres.tables.Conductor;
import ru.smartsarov.bus.postgres.tables.ConductorSchedule;
import ru.smartsarov.bus.postgres.tables.ConductorScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.ConductorSnapshot;
import ru.smartsarov.bus.postgres.tables.DepartureList;
import ru.smartsarov.bus.postgres.tables.DepartureMoments;
import ru.smartsarov.bus.postgres.tables.Driver;
import ru.smartsarov.bus.postgres.tables.DriverBrigade;
import ru.smartsarov.bus.postgres.tables.DriverGroup;
import ru.smartsarov.bus.postgres.tables.DriverSchedule;
import ru.smartsarov.bus.postgres.tables.DriverScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.DriverSnapshot;
import ru.smartsarov.bus.postgres.tables.EmployeeInfo;
import ru.smartsarov.bus.postgres.tables.FuelCode;
import ru.smartsarov.bus.postgres.tables.GenerationInfo;
import ru.smartsarov.bus.postgres.tables.Incident;
import ru.smartsarov.bus.postgres.tables.Race;
import ru.smartsarov.bus.postgres.tables.RaceSnaphot;
import ru.smartsarov.bus.postgres.tables.RbBusConditionType;
import ru.smartsarov.bus.postgres.tables.RbBusMake;
import ru.smartsarov.bus.postgres.tables.RbBusModel;
import ru.smartsarov.bus.postgres.tables.RbBusStop;
import ru.smartsarov.bus.postgres.tables.RbEmployeeScheduleType;
import ru.smartsarov.bus.postgres.tables.RbFuelType;
import ru.smartsarov.bus.postgres.tables.RbIncidentType;
import ru.smartsarov.bus.postgres.tables.RbPosition;
import ru.smartsarov.bus.postgres.tables.RbReadyType;
import ru.smartsarov.bus.postgres.tables.RbShiftType;
import ru.smartsarov.bus.postgres.tables.RbStateType;
import ru.smartsarov.bus.postgres.tables.Route;
import ru.smartsarov.bus.postgres.tables.RouteSchedule;
import ru.smartsarov.bus.postgres.tables.RouteScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.RouteSnapshot;
import ru.smartsarov.bus.postgres.tables.ShiftDepartureList;
import ru.smartsarov.bus.postgres.tables.ShiftDepartureMoments;
import ru.smartsarov.bus.postgres.tables.ShiftFixed;
import ru.smartsarov.bus.postgres.tables.ShiftFixedSnapshot;
import ru.smartsarov.bus.postgres.tables.ShiftSchedule;
import ru.smartsarov.bus.postgres.tables.ShiftScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.TechAvailability;
import ru.smartsarov.bus.postgres.tables.TechAvailabilitySnapshot;
import ru.smartsarov.bus.postgres.tables.Track;
import ru.smartsarov.bus.postgres.tables.TrackCoordinates;
import ru.smartsarov.bus.postgres.tables.User;
import ru.smartsarov.bus.postgres.tables.UserSession;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_BUS_TBL = Indexes0.PK_BUS_TBL;
    public static final Index PK_BUS_INFO_TBL = Indexes0.PK_BUS_INFO_TBL;
    public static final Index UNIQ_BUS_INFO_TBL_VIN = Indexes0.UNIQ_BUS_INFO_TBL_VIN;
    public static final Index PK_BUS_SNAPSHOT_TBL = Indexes0.PK_BUS_SNAPSHOT_TBL;
    public static final Index PK_BUS_STOP_LIST_TBL = Indexes0.PK_BUS_STOP_LIST_TBL;
    public static final Index PK_BUS_STOPS_TBL = Indexes0.PK_BUS_STOPS_TBL;
    public static final Index PK_COND_EMPLOYEE_INFO_TBL = Indexes0.PK_COND_EMPLOYEE_INFO_TBL;
    public static final Index PK_CONDUCTOR_TBL_ID = Indexes0.PK_CONDUCTOR_TBL_ID;
    public static final Index PK_CONDUCTOR_SCHEDULE_TBL = Indexes0.PK_CONDUCTOR_SCHEDULE_TBL;
    public static final Index PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL = Indexes0.PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL;
    public static final Index PK_CONDUCTOR_SNAPSHOT_TBL = Indexes0.PK_CONDUCTOR_SNAPSHOT_TBL;
    public static final Index PK_DEPARTURE_LIST_TBL = Indexes0.PK_DEPARTURE_LIST_TBL;
    public static final Index PK_DEPARTURE_MOMENTS_TBL = Indexes0.PK_DEPARTURE_MOMENTS_TBL;
    public static final Index PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID = Indexes0.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID;
    public static final Index PK_DRIVER_BRIGADE_TBL = Indexes0.PK_DRIVER_BRIGADE_TBL;
    public static final Index PK_DRIVER_GROUP_TBL = Indexes0.PK_DRIVER_GROUP_TBL;
    public static final Index PK_DRIVER_SCHEDULE_TBL = Indexes0.PK_DRIVER_SCHEDULE_TBL;
    public static final Index PK_DRIVER_SCHEDULE_SNAPSHOT_TBL = Indexes0.PK_DRIVER_SCHEDULE_SNAPSHOT_TBL;
    public static final Index PK_EMPLOYEE_SNAPSHOT_TBL = Indexes0.PK_EMPLOYEE_SNAPSHOT_TBL;
    public static final Index PK_EMPLOYEE_INFO_TBL = Indexes0.PK_EMPLOYEE_INFO_TBL;
    public static final Index PK_FUEL_CODE_TBL = Indexes0.PK_FUEL_CODE_TBL;
    public static final Index PK_GENERATION_INFO_TBL = Indexes0.PK_GENERATION_INFO_TBL;
    public static final Index PK_INCIDENT = Indexes0.PK_INCIDENT;
    public static final Index PK_RACE_TBL = Indexes0.PK_RACE_TBL;
    public static final Index PK_RACE_SNAPHOT_TBL = Indexes0.PK_RACE_SNAPHOT_TBL;
    public static final Index PK_BUS_CONDITION_TBL = Indexes0.PK_BUS_CONDITION_TBL;
    public static final Index PK_RB_BUS_MAKE_TBL = Indexes0.PK_RB_BUS_MAKE_TBL;
    public static final Index PK_RB_BUS_MODEL_TBL = Indexes0.PK_RB_BUS_MODEL_TBL;
    public static final Index PK_RB_BUS_STOP_TBL = Indexes0.PK_RB_BUS_STOP_TBL;
    public static final Index PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL = Indexes0.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL;
    public static final Index PL_RB_FUEL_TYPE_TBL = Indexes0.PL_RB_FUEL_TYPE_TBL;
    public static final Index PK_INCIDENT_TYPE_TBL = Indexes0.PK_INCIDENT_TYPE_TBL;
    public static final Index PK_RB_POSITION_TBL = Indexes0.PK_RB_POSITION_TBL;
    public static final Index PK_RB_READY_TYPE_TBL = Indexes0.PK_RB_READY_TYPE_TBL;
    public static final Index PK_SHIFT_TYPE_TBL = Indexes0.PK_SHIFT_TYPE_TBL;
    public static final Index PK_RB_STATE_TYPE_TBL = Indexes0.PK_RB_STATE_TYPE_TBL;
    public static final Index PK_ROUTE_TBL = Indexes0.PK_ROUTE_TBL;
    public static final Index PK_ROUTE_SCHEDULE_TBL = Indexes0.PK_ROUTE_SCHEDULE_TBL;
    public static final Index UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = Indexes0.UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID;
    public static final Index PK_ROUTE_SCHEDULE_SNAPSHOT_TBL = Indexes0.PK_ROUTE_SCHEDULE_SNAPSHOT_TBL;
    public static final Index PK_ROUTE_SNAPSOT_TBL = Indexes0.PK_ROUTE_SNAPSOT_TBL;
    public static final Index PK_SHIFT_DEPARTURE_LIST_TBL = Indexes0.PK_SHIFT_DEPARTURE_LIST_TBL;
    public static final Index PK_SHIFT_DEPARTURE_MOMENTS_TBL = Indexes0.PK_SHIFT_DEPARTURE_MOMENTS_TBL;
    public static final Index PK_SHIFT_FIXED_TBL = Indexes0.PK_SHIFT_FIXED_TBL;
    public static final Index PK_FIXED_SHIFT_SNAPSHOT_TBL = Indexes0.PK_FIXED_SHIFT_SNAPSHOT_TBL;
    public static final Index PK_SHIFT_SCHEDULE_ID = Indexes0.PK_SHIFT_SCHEDULE_ID;
    public static final Index PK_SHIFT_SCHEDULE_SNAPSORT_TBL = Indexes0.PK_SHIFT_SCHEDULE_SNAPSORT_TBL;
    public static final Index PK_TECH_AVAILABILITY_TBL = Indexes0.PK_TECH_AVAILABILITY_TBL;
    public static final Index PK_TECH_SNAPSHOT_AVAILABILITY_TBL = Indexes0.PK_TECH_SNAPSHOT_AVAILABILITY_TBL;
    public static final Index PK_TRACK_TBL = Indexes0.PK_TRACK_TBL;
    public static final Index PK_TRACK_COORDINATES_TBL = Indexes0.PK_TRACK_COORDINATES_TBL;
    public static final Index PK_USER_ID = Indexes0.PK_USER_ID;
    public static final Index PK_USER_SESSION_TBL = Indexes0.PK_USER_SESSION_TBL;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_BUS_TBL = Internal.createIndex("pk_bus_tbl", Bus.BUS, new OrderField[] { Bus.BUS.ID }, true);
        public static Index PK_BUS_INFO_TBL = Internal.createIndex("pk_bus_info_tbl", BusInfo.BUS_INFO, new OrderField[] { BusInfo.BUS_INFO.ID }, true);
        public static Index UNIQ_BUS_INFO_TBL_VIN = Internal.createIndex("uniq_bus_info_tbl_vin", BusInfo.BUS_INFO, new OrderField[] { BusInfo.BUS_INFO.VIN }, true);
        public static Index PK_BUS_SNAPSHOT_TBL = Internal.createIndex("pk_bus_snapshot_tbl", BusSnapshot.BUS_SNAPSHOT, new OrderField[] { BusSnapshot.BUS_SNAPSHOT.ID, BusSnapshot.BUS_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_BUS_STOP_LIST_TBL = Internal.createIndex("pk_bus_stop_list_tbl", BusStopList.BUS_STOP_LIST, new OrderField[] { BusStopList.BUS_STOP_LIST.ID }, true);
        public static Index PK_BUS_STOPS_TBL = Internal.createIndex("pk_bus_stops_tbl", BusStops.BUS_STOPS, new OrderField[] { BusStops.BUS_STOPS.ID }, true);
        public static Index PK_COND_EMPLOYEE_INFO_TBL = Internal.createIndex("pk_cond_employee_info_tbl", CondEmployeeInfo.COND_EMPLOYEE_INFO, new OrderField[] { CondEmployeeInfo.COND_EMPLOYEE_INFO.ID }, true);
        public static Index PK_CONDUCTOR_TBL_ID = Internal.createIndex("pk_conductor_tbl_id", Conductor.CONDUCTOR, new OrderField[] { Conductor.CONDUCTOR.ID }, true);
        public static Index PK_CONDUCTOR_SCHEDULE_TBL = Internal.createIndex("pk_conductor_schedule_tbl", ConductorSchedule.CONDUCTOR_SCHEDULE, new OrderField[] { ConductorSchedule.CONDUCTOR_SCHEDULE.CONDUCTOR_ID, ConductorSchedule.CONDUCTOR_SCHEDULE.DATE }, true);
        public static Index PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL = Internal.createIndex("pk_conductor_schedule_snapshot_tbl", ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT, new OrderField[] { ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.CONDUCTOR_ID, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.DATE, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_CONDUCTOR_SNAPSHOT_TBL = Internal.createIndex("pk_conductor_snapshot_tbl", ConductorSnapshot.CONDUCTOR_SNAPSHOT, new OrderField[] { ConductorSnapshot.CONDUCTOR_SNAPSHOT.ID, ConductorSnapshot.CONDUCTOR_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_DEPARTURE_LIST_TBL = Internal.createIndex("pk_departure_list_tbl", DepartureList.DEPARTURE_LIST, new OrderField[] { DepartureList.DEPARTURE_LIST.ID }, true);
        public static Index PK_DEPARTURE_MOMENTS_TBL = Internal.createIndex("pk_departure_moments_tbl", DepartureMoments.DEPARTURE_MOMENTS, new OrderField[] { DepartureMoments.DEPARTURE_MOMENTS.ID }, true);
        public static Index PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID = Internal.createIndex("pk_driver_tbl_employee_snapshot_id", Driver.DRIVER, new OrderField[] { Driver.DRIVER.ID }, true);
        public static Index PK_DRIVER_BRIGADE_TBL = Internal.createIndex("pk_driver_brigade_tbl", DriverBrigade.DRIVER_BRIGADE, new OrderField[] { DriverBrigade.DRIVER_BRIGADE.ID }, true);
        public static Index PK_DRIVER_GROUP_TBL = Internal.createIndex("pk_driver_group_tbl", DriverGroup.DRIVER_GROUP, new OrderField[] { DriverGroup.DRIVER_GROUP.ID }, true);
        public static Index PK_DRIVER_SCHEDULE_TBL = Internal.createIndex("pk_driver_schedule_tbl", DriverSchedule.DRIVER_SCHEDULE, new OrderField[] { DriverSchedule.DRIVER_SCHEDULE.DRIVER_ID, DriverSchedule.DRIVER_SCHEDULE.DATE }, true);
        public static Index PK_DRIVER_SCHEDULE_SNAPSHOT_TBL = Internal.createIndex("pk_driver_schedule_snapshot_tbl", DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT, new OrderField[] { DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.DRIVER_ID, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.DATE, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_EMPLOYEE_SNAPSHOT_TBL = Internal.createIndex("pk_employee_snapshot_tbl", DriverSnapshot.DRIVER_SNAPSHOT, new OrderField[] { DriverSnapshot.DRIVER_SNAPSHOT.ID, DriverSnapshot.DRIVER_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_EMPLOYEE_INFO_TBL = Internal.createIndex("pk_employee_info_tbl", EmployeeInfo.EMPLOYEE_INFO, new OrderField[] { EmployeeInfo.EMPLOYEE_INFO.ID }, true);
        public static Index PK_FUEL_CODE_TBL = Internal.createIndex("pk_fuel_code_tbl", FuelCode.FUEL_CODE, new OrderField[] { FuelCode.FUEL_CODE.ID }, true);
        public static Index PK_GENERATION_INFO_TBL = Internal.createIndex("pk_generation_info_tbl", GenerationInfo.GENERATION_INFO, new OrderField[] { GenerationInfo.GENERATION_INFO.DATE }, true);
        public static Index PK_INCIDENT = Internal.createIndex("pk_incident", Incident.INCIDENT, new OrderField[] { Incident.INCIDENT.ID }, true);
        public static Index PK_RACE_TBL = Internal.createIndex("pk_race_tbl", Race.RACE, new OrderField[] { Race.RACE.ID }, true);
        public static Index PK_RACE_SNAPHOT_TBL = Internal.createIndex("pk_race_snaphot_tbl", RaceSnaphot.RACE_SNAPHOT, new OrderField[] { RaceSnaphot.RACE_SNAPHOT.ID, RaceSnaphot.RACE_SNAPHOT.CREATED_AT }, true);
        public static Index PK_BUS_CONDITION_TBL = Internal.createIndex("pk_bus_condition_tbl", RbBusConditionType.RB_BUS_CONDITION_TYPE, new OrderField[] { RbBusConditionType.RB_BUS_CONDITION_TYPE.ID }, true);
        public static Index PK_RB_BUS_MAKE_TBL = Internal.createIndex("pk_rb_bus_make_tbl", RbBusMake.RB_BUS_MAKE, new OrderField[] { RbBusMake.RB_BUS_MAKE.ID }, true);
        public static Index PK_RB_BUS_MODEL_TBL = Internal.createIndex("pk_rb_bus_model_tbl", RbBusModel.RB_BUS_MODEL, new OrderField[] { RbBusModel.RB_BUS_MODEL.ID }, true);
        public static Index PK_RB_BUS_STOP_TBL = Internal.createIndex("pk_rb_bus_stop_tbl", RbBusStop.RB_BUS_STOP, new OrderField[] { RbBusStop.RB_BUS_STOP.ID }, true);
        public static Index PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL = Internal.createIndex("pk_rb_employee_schedule_type_tbl", RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE, new OrderField[] { RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE.ID }, true);
        public static Index PL_RB_FUEL_TYPE_TBL = Internal.createIndex("pl_rb_fuel_type_tbl", RbFuelType.RB_FUEL_TYPE, new OrderField[] { RbFuelType.RB_FUEL_TYPE.ID }, true);
        public static Index PK_INCIDENT_TYPE_TBL = Internal.createIndex("pk_incident_type_tbl", RbIncidentType.RB_INCIDENT_TYPE, new OrderField[] { RbIncidentType.RB_INCIDENT_TYPE.ID }, true);
        public static Index PK_RB_POSITION_TBL = Internal.createIndex("pk_rb_position_tbl", RbPosition.RB_POSITION, new OrderField[] { RbPosition.RB_POSITION.ID }, true);
        public static Index PK_RB_READY_TYPE_TBL = Internal.createIndex("pk_rb_ready_type_tbl", RbReadyType.RB_READY_TYPE, new OrderField[] { RbReadyType.RB_READY_TYPE.ID }, true);
        public static Index PK_SHIFT_TYPE_TBL = Internal.createIndex("pk_shift_type_tbl", RbShiftType.RB_SHIFT_TYPE, new OrderField[] { RbShiftType.RB_SHIFT_TYPE.ID }, true);
        public static Index PK_RB_STATE_TYPE_TBL = Internal.createIndex("pk_rb_state_type_tbl", RbStateType.RB_STATE_TYPE, new OrderField[] { RbStateType.RB_STATE_TYPE.ID }, true);
        public static Index PK_ROUTE_TBL = Internal.createIndex("pk_route_tbl", Route.ROUTE, new OrderField[] { Route.ROUTE.ID }, true);
        public static Index PK_ROUTE_SCHEDULE_TBL = Internal.createIndex("pk_route_schedule_tbl", RouteSchedule.ROUTE_SCHEDULE, new OrderField[] { RouteSchedule.ROUTE_SCHEDULE.ROUTE_ID }, true);
        public static Index UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = Internal.createIndex("uniq_route_schedule_tbl_departure_list_id", RouteSchedule.ROUTE_SCHEDULE, new OrderField[] { RouteSchedule.ROUTE_SCHEDULE.DEPARTURE_LIST_ID }, true);
        public static Index PK_ROUTE_SCHEDULE_SNAPSHOT_TBL = Internal.createIndex("pk_route_schedule_snapshot_tbl", RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT, new OrderField[] { RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.ROUTE_ID, RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_ROUTE_SNAPSOT_TBL = Internal.createIndex("pk_route_snapsot_tbl", RouteSnapshot.ROUTE_SNAPSHOT, new OrderField[] { RouteSnapshot.ROUTE_SNAPSHOT.ID, RouteSnapshot.ROUTE_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_SHIFT_DEPARTURE_LIST_TBL = Internal.createIndex("pk_shift_departure_list_tbl", ShiftDepartureList.SHIFT_DEPARTURE_LIST, new OrderField[] { ShiftDepartureList.SHIFT_DEPARTURE_LIST.ID }, true);
        public static Index PK_SHIFT_DEPARTURE_MOMENTS_TBL = Internal.createIndex("pk_shift_departure_moments_tbl", ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS, new OrderField[] { ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS.ID }, true);
        public static Index PK_SHIFT_FIXED_TBL = Internal.createIndex("pk_shift_fixed_tbl", ShiftFixed.SHIFT_FIXED, new OrderField[] { ShiftFixed.SHIFT_FIXED.SHIFT_SCHEDULE_ID, ShiftFixed.SHIFT_FIXED.DATE }, true);
        public static Index PK_FIXED_SHIFT_SNAPSHOT_TBL = Internal.createIndex("pk_fixed_shift_snapshot_tbl", ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT, new OrderField[] { ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.SHIFT_SCHEDULE_ID, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.DATE, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_SHIFT_SCHEDULE_ID = Internal.createIndex("pk_shift_schedule_id", ShiftSchedule.SHIFT_SCHEDULE, new OrderField[] { ShiftSchedule.SHIFT_SCHEDULE.ID }, true);
        public static Index PK_SHIFT_SCHEDULE_SNAPSORT_TBL = Internal.createIndex("pk_shift_schedule_snapsort_tbl", ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT, new OrderField[] { ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.ID, ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_TECH_AVAILABILITY_TBL = Internal.createIndex("pk_tech_availability_tbl", TechAvailability.TECH_AVAILABILITY, new OrderField[] { TechAvailability.TECH_AVAILABILITY.BUS_ID, TechAvailability.TECH_AVAILABILITY.DATE }, true);
        public static Index PK_TECH_SNAPSHOT_AVAILABILITY_TBL = Internal.createIndex("pk_tech_snapshot_availability_tbl", TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT, new OrderField[] { TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.BUS_ID, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.DATE, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.CREATED_AT }, true);
        public static Index PK_TRACK_TBL = Internal.createIndex("pk_track_tbl", Track.TRACK, new OrderField[] { Track.TRACK.ID }, true);
        public static Index PK_TRACK_COORDINATES_TBL = Internal.createIndex("pk_track_coordinates_tbl", TrackCoordinates.TRACK_COORDINATES, new OrderField[] { TrackCoordinates.TRACK_COORDINATES.ID }, true);
        public static Index PK_USER_ID = Internal.createIndex("pk_user_id", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index PK_USER_SESSION_TBL = Internal.createIndex("pk_user_session_tbl", UserSession.USER_SESSION, new OrderField[] { UserSession.USER_SESSION.ID }, true);
    }
}
