/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.smartsarov.bus.postgres.tables.Bus;
import ru.smartsarov.bus.postgres.tables.BusInfo;
import ru.smartsarov.bus.postgres.tables.BusSnapshot;
import ru.smartsarov.bus.postgres.tables.BusStopList;
import ru.smartsarov.bus.postgres.tables.BusStops;
import ru.smartsarov.bus.postgres.tables.Conductor;
import ru.smartsarov.bus.postgres.tables.ConductorSchedule;
import ru.smartsarov.bus.postgres.tables.ConductorScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.ConductorSnapshot;
import ru.smartsarov.bus.postgres.tables.DepartureList;
import ru.smartsarov.bus.postgres.tables.DepartureMoments;
import ru.smartsarov.bus.postgres.tables.Driver;
import ru.smartsarov.bus.postgres.tables.DriverBrigade;
import ru.smartsarov.bus.postgres.tables.DriverGroup;
import ru.smartsarov.bus.postgres.tables.DriverSchedule;
import ru.smartsarov.bus.postgres.tables.DriverScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.DriverSnapshot;
import ru.smartsarov.bus.postgres.tables.EmployeeInfo;
import ru.smartsarov.bus.postgres.tables.FuelCode;
import ru.smartsarov.bus.postgres.tables.Intsident;
import ru.smartsarov.bus.postgres.tables.Position;
import ru.smartsarov.bus.postgres.tables.Race;
import ru.smartsarov.bus.postgres.tables.RaceSnaphot;
import ru.smartsarov.bus.postgres.tables.RbBusConditionType;
import ru.smartsarov.bus.postgres.tables.RbBusMake;
import ru.smartsarov.bus.postgres.tables.RbBusModel;
import ru.smartsarov.bus.postgres.tables.RbBusStop;
import ru.smartsarov.bus.postgres.tables.RbEmployeeScheduleType;
import ru.smartsarov.bus.postgres.tables.RbEmployeeType;
import ru.smartsarov.bus.postgres.tables.RbFuelType;
import ru.smartsarov.bus.postgres.tables.RbIntsidentType;
import ru.smartsarov.bus.postgres.tables.RbReadyType;
import ru.smartsarov.bus.postgres.tables.RbStateType;
import ru.smartsarov.bus.postgres.tables.Route;
import ru.smartsarov.bus.postgres.tables.RouteSchedule;
import ru.smartsarov.bus.postgres.tables.RouteScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.RouteSnapshot;
import ru.smartsarov.bus.postgres.tables.ShiftDepartureList;
import ru.smartsarov.bus.postgres.tables.ShiftDepartureMoments;
import ru.smartsarov.bus.postgres.tables.ShiftFixed;
import ru.smartsarov.bus.postgres.tables.ShiftFixedSnapshot;
import ru.smartsarov.bus.postgres.tables.ShiftSchedule;
import ru.smartsarov.bus.postgres.tables.ShiftScheduleSnapshot;
import ru.smartsarov.bus.postgres.tables.ShiftType;
import ru.smartsarov.bus.postgres.tables.TechAvailability;
import ru.smartsarov.bus.postgres.tables.TechAvailabilitySnapshot;
import ru.smartsarov.bus.postgres.tables.Track;
import ru.smartsarov.bus.postgres.tables.TrackCoordinates;
import ru.smartsarov.bus.postgres.tables.records.BusInfoRecord;
import ru.smartsarov.bus.postgres.tables.records.BusRecord;
import ru.smartsarov.bus.postgres.tables.records.BusSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.BusStopListRecord;
import ru.smartsarov.bus.postgres.tables.records.BusStopsRecord;
import ru.smartsarov.bus.postgres.tables.records.ConductorRecord;
import ru.smartsarov.bus.postgres.tables.records.ConductorScheduleRecord;
import ru.smartsarov.bus.postgres.tables.records.ConductorScheduleSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.ConductorSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.DepartureListRecord;
import ru.smartsarov.bus.postgres.tables.records.DepartureMomentsRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverBrigadeRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverGroupRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverScheduleRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverScheduleSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.DriverSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.EmployeeInfoRecord;
import ru.smartsarov.bus.postgres.tables.records.FuelCodeRecord;
import ru.smartsarov.bus.postgres.tables.records.IntsidentRecord;
import ru.smartsarov.bus.postgres.tables.records.PositionRecord;
import ru.smartsarov.bus.postgres.tables.records.RaceRecord;
import ru.smartsarov.bus.postgres.tables.records.RaceSnaphotRecord;
import ru.smartsarov.bus.postgres.tables.records.RbBusConditionTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbBusMakeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbBusModelRecord;
import ru.smartsarov.bus.postgres.tables.records.RbBusStopRecord;
import ru.smartsarov.bus.postgres.tables.records.RbEmployeeScheduleTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbEmployeeTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbFuelTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbIntsidentTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbReadyTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RbStateTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.RouteRecord;
import ru.smartsarov.bus.postgres.tables.records.RouteScheduleRecord;
import ru.smartsarov.bus.postgres.tables.records.RouteScheduleSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.RouteSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftDepartureListRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftDepartureMomentsRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftFixedRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftFixedSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftScheduleRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftScheduleSnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.ShiftTypeRecord;
import ru.smartsarov.bus.postgres.tables.records.TechAvailabilityRecord;
import ru.smartsarov.bus.postgres.tables.records.TechAvailabilitySnapshotRecord;
import ru.smartsarov.bus.postgres.tables.records.TrackCoordinatesRecord;
import ru.smartsarov.bus.postgres.tables.records.TrackRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BusRecord, Integer> IDENTITY_BUS = Identities0.IDENTITY_BUS;
    public static final Identity<BusInfoRecord, Short> IDENTITY_BUS_INFO = Identities0.IDENTITY_BUS_INFO;
    public static final Identity<BusSnapshotRecord, Integer> IDENTITY_BUS_SNAPSHOT = Identities0.IDENTITY_BUS_SNAPSHOT;
    public static final Identity<BusStopListRecord, Integer> IDENTITY_BUS_STOP_LIST = Identities0.IDENTITY_BUS_STOP_LIST;
    public static final Identity<BusStopsRecord, Integer> IDENTITY_BUS_STOPS = Identities0.IDENTITY_BUS_STOPS;
    public static final Identity<ConductorRecord, Integer> IDENTITY_CONDUCTOR = Identities0.IDENTITY_CONDUCTOR;
    public static final Identity<ConductorSnapshotRecord, Integer> IDENTITY_CONDUCTOR_SNAPSHOT = Identities0.IDENTITY_CONDUCTOR_SNAPSHOT;
    public static final Identity<DepartureListRecord, Integer> IDENTITY_DEPARTURE_LIST = Identities0.IDENTITY_DEPARTURE_LIST;
    public static final Identity<DepartureMomentsRecord, Integer> IDENTITY_DEPARTURE_MOMENTS = Identities0.IDENTITY_DEPARTURE_MOMENTS;
    public static final Identity<DriverRecord, Integer> IDENTITY_DRIVER = Identities0.IDENTITY_DRIVER;
    public static final Identity<DriverBrigadeRecord, Short> IDENTITY_DRIVER_BRIGADE = Identities0.IDENTITY_DRIVER_BRIGADE;
    public static final Identity<DriverGroupRecord, Short> IDENTITY_DRIVER_GROUP = Identities0.IDENTITY_DRIVER_GROUP;
    public static final Identity<DriverSnapshotRecord, Integer> IDENTITY_DRIVER_SNAPSHOT = Identities0.IDENTITY_DRIVER_SNAPSHOT;
    public static final Identity<EmployeeInfoRecord, Short> IDENTITY_EMPLOYEE_INFO = Identities0.IDENTITY_EMPLOYEE_INFO;
    public static final Identity<FuelCodeRecord, Integer> IDENTITY_FUEL_CODE = Identities0.IDENTITY_FUEL_CODE;
    public static final Identity<IntsidentRecord, Integer> IDENTITY_INTSIDENT = Identities0.IDENTITY_INTSIDENT;
    public static final Identity<PositionRecord, Integer> IDENTITY_POSITION = Identities0.IDENTITY_POSITION;
    public static final Identity<RaceRecord, Integer> IDENTITY_RACE = Identities0.IDENTITY_RACE;
    public static final Identity<RaceSnaphotRecord, Integer> IDENTITY_RACE_SNAPHOT = Identities0.IDENTITY_RACE_SNAPHOT;
    public static final Identity<RbBusConditionTypeRecord, Short> IDENTITY_RB_BUS_CONDITION_TYPE = Identities0.IDENTITY_RB_BUS_CONDITION_TYPE;
    public static final Identity<RbBusMakeRecord, Short> IDENTITY_RB_BUS_MAKE = Identities0.IDENTITY_RB_BUS_MAKE;
    public static final Identity<RbBusModelRecord, Short> IDENTITY_RB_BUS_MODEL = Identities0.IDENTITY_RB_BUS_MODEL;
    public static final Identity<RbBusStopRecord, Integer> IDENTITY_RB_BUS_STOP = Identities0.IDENTITY_RB_BUS_STOP;
    public static final Identity<RbEmployeeScheduleTypeRecord, Integer> IDENTITY_RB_EMPLOYEE_SCHEDULE_TYPE = Identities0.IDENTITY_RB_EMPLOYEE_SCHEDULE_TYPE;
    public static final Identity<RbEmployeeTypeRecord, Integer> IDENTITY_RB_EMPLOYEE_TYPE = Identities0.IDENTITY_RB_EMPLOYEE_TYPE;
    public static final Identity<RbFuelTypeRecord, Integer> IDENTITY_RB_FUEL_TYPE = Identities0.IDENTITY_RB_FUEL_TYPE;
    public static final Identity<RbReadyTypeRecord, Integer> IDENTITY_RB_READY_TYPE = Identities0.IDENTITY_RB_READY_TYPE;
    public static final Identity<RbStateTypeRecord, Short> IDENTITY_RB_STATE_TYPE = Identities0.IDENTITY_RB_STATE_TYPE;
    public static final Identity<RouteRecord, Integer> IDENTITY_ROUTE = Identities0.IDENTITY_ROUTE;
    public static final Identity<ShiftDepartureListRecord, Integer> IDENTITY_SHIFT_DEPARTURE_LIST = Identities0.IDENTITY_SHIFT_DEPARTURE_LIST;
    public static final Identity<ShiftDepartureMomentsRecord, Integer> IDENTITY_SHIFT_DEPARTURE_MOMENTS = Identities0.IDENTITY_SHIFT_DEPARTURE_MOMENTS;
    public static final Identity<ShiftScheduleRecord, Integer> IDENTITY_SHIFT_SCHEDULE = Identities0.IDENTITY_SHIFT_SCHEDULE;
    public static final Identity<ShiftScheduleSnapshotRecord, Integer> IDENTITY_SHIFT_SCHEDULE_SNAPSHOT = Identities0.IDENTITY_SHIFT_SCHEDULE_SNAPSHOT;
    public static final Identity<ShiftTypeRecord, Integer> IDENTITY_SHIFT_TYPE = Identities0.IDENTITY_SHIFT_TYPE;
    public static final Identity<TrackRecord, Integer> IDENTITY_TRACK = Identities0.IDENTITY_TRACK;
    public static final Identity<TrackCoordinatesRecord, Integer> IDENTITY_TRACK_COORDINATES = Identities0.IDENTITY_TRACK_COORDINATES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BusRecord> PK_BUS_TBL = UniqueKeys0.PK_BUS_TBL;
    public static final UniqueKey<BusInfoRecord> PK_BUS_INFO_TBL = UniqueKeys0.PK_BUS_INFO_TBL;
    public static final UniqueKey<BusInfoRecord> UNIQ_BUS_INFO_TBL_VIN = UniqueKeys0.UNIQ_BUS_INFO_TBL_VIN;
    public static final UniqueKey<BusSnapshotRecord> PK_BUS_SNAPSHOT_TBL = UniqueKeys0.PK_BUS_SNAPSHOT_TBL;
    public static final UniqueKey<BusStopListRecord> PK_BUS_STOP_LIST_TBL = UniqueKeys0.PK_BUS_STOP_LIST_TBL;
    public static final UniqueKey<BusStopsRecord> PK_BUS_STOPS_TBL = UniqueKeys0.PK_BUS_STOPS_TBL;
    public static final UniqueKey<ConductorRecord> PK_CONDUCTOR_TBL_ID = UniqueKeys0.PK_CONDUCTOR_TBL_ID;
    public static final UniqueKey<ConductorScheduleRecord> PK_CONDUCTOR_SCHEDULE_TBL = UniqueKeys0.PK_CONDUCTOR_SCHEDULE_TBL;
    public static final UniqueKey<ConductorScheduleSnapshotRecord> PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL = UniqueKeys0.PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL;
    public static final UniqueKey<ConductorSnapshotRecord> PK_CONDUCTOR_SNAPSHOT_TBL = UniqueKeys0.PK_CONDUCTOR_SNAPSHOT_TBL;
    public static final UniqueKey<DepartureListRecord> PK_DEPARTURE_LIST_TBL = UniqueKeys0.PK_DEPARTURE_LIST_TBL;
    public static final UniqueKey<DepartureMomentsRecord> PK_DEPARTURE_MOMENTS_TBL = UniqueKeys0.PK_DEPARTURE_MOMENTS_TBL;
    public static final UniqueKey<DriverRecord> PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID = UniqueKeys0.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID;
    public static final UniqueKey<DriverBrigadeRecord> PK_DRIVER_BRIGADE_TBL = UniqueKeys0.PK_DRIVER_BRIGADE_TBL;
    public static final UniqueKey<DriverGroupRecord> PK_DRIVER_GROUP_TBL = UniqueKeys0.PK_DRIVER_GROUP_TBL;
    public static final UniqueKey<DriverScheduleRecord> PK_DRIVER_SCHEDULE_TBL = UniqueKeys0.PK_DRIVER_SCHEDULE_TBL;
    public static final UniqueKey<DriverScheduleSnapshotRecord> PK_DRIVER_SCHEDULE_SNAPSHOT_TBL = UniqueKeys0.PK_DRIVER_SCHEDULE_SNAPSHOT_TBL;
    public static final UniqueKey<DriverSnapshotRecord> PK_EMPLOYEE_SNAPSHOT_TBL = UniqueKeys0.PK_EMPLOYEE_SNAPSHOT_TBL;
    public static final UniqueKey<EmployeeInfoRecord> PK_EMPLOYEE_INFO_TBL = UniqueKeys0.PK_EMPLOYEE_INFO_TBL;
    public static final UniqueKey<FuelCodeRecord> PK_FUEL_CODE_TBL = UniqueKeys0.PK_FUEL_CODE_TBL;
    public static final UniqueKey<IntsidentRecord> PK_INTSIDENT = UniqueKeys0.PK_INTSIDENT;
    public static final UniqueKey<PositionRecord> PK_POSITION_TBL = UniqueKeys0.PK_POSITION_TBL;
    public static final UniqueKey<RaceRecord> PK_RACE_TBL = UniqueKeys0.PK_RACE_TBL;
    public static final UniqueKey<RaceSnaphotRecord> PK_RACE_SNAPHOT_TBL = UniqueKeys0.PK_RACE_SNAPHOT_TBL;
    public static final UniqueKey<RbBusConditionTypeRecord> PK_BUS_CONDITION_TBL = UniqueKeys0.PK_BUS_CONDITION_TBL;
    public static final UniqueKey<RbBusMakeRecord> PK_RB_BUS_MAKE_TBL = UniqueKeys0.PK_RB_BUS_MAKE_TBL;
    public static final UniqueKey<RbBusModelRecord> PK_RB_BUS_MODEL_TBL = UniqueKeys0.PK_RB_BUS_MODEL_TBL;
    public static final UniqueKey<RbBusStopRecord> PK_RB_BUS_STOP_TBL = UniqueKeys0.PK_RB_BUS_STOP_TBL;
    public static final UniqueKey<RbEmployeeScheduleTypeRecord> PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL = UniqueKeys0.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL;
    public static final UniqueKey<RbEmployeeTypeRecord> PK_RB_EMPLOYEE_TYPE_TBL = UniqueKeys0.PK_RB_EMPLOYEE_TYPE_TBL;
    public static final UniqueKey<RbFuelTypeRecord> PL_RB_FUEL_TYPE_TBL = UniqueKeys0.PL_RB_FUEL_TYPE_TBL;
    public static final UniqueKey<RbIntsidentTypeRecord> PK_INTSIDENT_TYPE_TBL = UniqueKeys0.PK_INTSIDENT_TYPE_TBL;
    public static final UniqueKey<RbReadyTypeRecord> PK_RB_READY_TYPE_TBL = UniqueKeys0.PK_RB_READY_TYPE_TBL;
    public static final UniqueKey<RbStateTypeRecord> PK_RB_STATE_TYPE_TBL = UniqueKeys0.PK_RB_STATE_TYPE_TBL;
    public static final UniqueKey<RouteRecord> PK_ROUTE_TBL = UniqueKeys0.PK_ROUTE_TBL;
    public static final UniqueKey<RouteScheduleRecord> PK_ROUTE_SCHEDULE_TBL = UniqueKeys0.PK_ROUTE_SCHEDULE_TBL;
    public static final UniqueKey<RouteScheduleRecord> UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = UniqueKeys0.UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID;
    public static final UniqueKey<RouteScheduleSnapshotRecord> PK_ROUTE_SCHEDULE_SNAPSHOT_TBL = UniqueKeys0.PK_ROUTE_SCHEDULE_SNAPSHOT_TBL;
    public static final UniqueKey<RouteSnapshotRecord> PK_ROUTE_SNAPSOT_TBL = UniqueKeys0.PK_ROUTE_SNAPSOT_TBL;
    public static final UniqueKey<ShiftDepartureListRecord> PK_SHIFT_DEPARTURE_LIST_TBL = UniqueKeys0.PK_SHIFT_DEPARTURE_LIST_TBL;
    public static final UniqueKey<ShiftDepartureMomentsRecord> PK_SHIFT_DEPARTURE_MOMENTS_TBL = UniqueKeys0.PK_SHIFT_DEPARTURE_MOMENTS_TBL;
    public static final UniqueKey<ShiftFixedRecord> PK_SHIFT_FIXED_TBL = UniqueKeys0.PK_SHIFT_FIXED_TBL;
    public static final UniqueKey<ShiftFixedSnapshotRecord> PK_FIXED_SHIFT_SNAPSHOT_TBL = UniqueKeys0.PK_FIXED_SHIFT_SNAPSHOT_TBL;
    public static final UniqueKey<ShiftScheduleRecord> PK_SHIFT_SCHEDULE_ID = UniqueKeys0.PK_SHIFT_SCHEDULE_ID;
    public static final UniqueKey<ShiftScheduleSnapshotRecord> PK_SHIFT_SCHEDULE_SNAPSORT_TBL = UniqueKeys0.PK_SHIFT_SCHEDULE_SNAPSORT_TBL;
    public static final UniqueKey<ShiftTypeRecord> PK_SHIFT_TYPE_TBL = UniqueKeys0.PK_SHIFT_TYPE_TBL;
    public static final UniqueKey<TechAvailabilityRecord> PK_TECH_AVAILABILITY_TBL = UniqueKeys0.PK_TECH_AVAILABILITY_TBL;
    public static final UniqueKey<TechAvailabilitySnapshotRecord> PK_TECH_SNAPSHOT_AVAILABILITY_TBL = UniqueKeys0.PK_TECH_SNAPSHOT_AVAILABILITY_TBL;
    public static final UniqueKey<TrackRecord> PK_TRACK_TBL = UniqueKeys0.PK_TRACK_TBL;
    public static final UniqueKey<TrackCoordinatesRecord> PK_TRACK_COORDINATES_TBL = UniqueKeys0.PK_TRACK_COORDINATES_TBL;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BusRecord, BusInfoRecord> BUS__FK_BUS_TBL_BUS_INFO_ID = ForeignKeys0.BUS__FK_BUS_TBL_BUS_INFO_ID;
    public static final ForeignKey<BusRecord, FuelCodeRecord> BUS__FK_BUS_TBL_FUEL_CODE_ID = ForeignKeys0.BUS__FK_BUS_TBL_FUEL_CODE_ID;
    public static final ForeignKey<BusRecord, RbBusConditionTypeRecord> BUS__FK_BUS_TBL_CONDITION_ID = ForeignKeys0.BUS__FK_BUS_TBL_CONDITION_ID;
    public static final ForeignKey<BusInfoRecord, RbBusMakeRecord> BUS_INFO__FK_BUS_INFO_TBL_BUS_MAKE = ForeignKeys0.BUS_INFO__FK_BUS_INFO_TBL_BUS_MAKE;
    public static final ForeignKey<BusInfoRecord, RbBusModelRecord> BUS_INFO__FK_BUS_INFO_TBL_BUS_MODEL = ForeignKeys0.BUS_INFO__FK_BUS_INFO_TBL_BUS_MODEL;
    public static final ForeignKey<BusSnapshotRecord, BusInfoRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_BUS_ID = ForeignKeys0.BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_BUS_ID;
    public static final ForeignKey<BusSnapshotRecord, FuelCodeRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_FUEL_CODE_ID = ForeignKeys0.BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_FUEL_CODE_ID;
    public static final ForeignKey<BusSnapshotRecord, RbBusConditionTypeRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_CONDITION_ID = ForeignKeys0.BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_CONDITION_ID;
    public static final ForeignKey<BusStopsRecord, BusStopListRecord> BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_LIST_ID = ForeignKeys0.BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_LIST_ID;
    public static final ForeignKey<BusStopsRecord, RbBusStopRecord> BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_ID = ForeignKeys0.BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_ID;
    public static final ForeignKey<ConductorRecord, RbEmployeeScheduleTypeRecord> CONDUCTOR__FK_CONDUCTOR_TBL_SCHEDULE_TYPE_ID_FK = ForeignKeys0.CONDUCTOR__FK_CONDUCTOR_TBL_SCHEDULE_TYPE_ID_FK;
    public static final ForeignKey<ConductorRecord, EmployeeInfoRecord> CONDUCTOR__FK_CONDUCTOR_TBL_EMPLOYEE_DATA_ID = ForeignKeys0.CONDUCTOR__FK_CONDUCTOR_TBL_EMPLOYEE_DATA_ID;
    public static final ForeignKey<ConductorRecord, PositionRecord> CONDUCTOR__FK_CONDUCTOR_TBL_POSITION_ID = ForeignKeys0.CONDUCTOR__FK_CONDUCTOR_TBL_POSITION_ID;
    public static final ForeignKey<ConductorRecord, RbStateTypeRecord> CONDUCTOR__FK_CONDUCTOR_TBL_STATE_ID_FK = ForeignKeys0.CONDUCTOR__FK_CONDUCTOR_TBL_STATE_ID_FK;
    public static final ForeignKey<ConductorScheduleRecord, ConductorRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_CONDUCTOR_ID = ForeignKeys0.CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_CONDUCTOR_ID;
    public static final ForeignKey<ConductorScheduleRecord, ShiftTypeRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_SHIFT_TYPE_ID = ForeignKeys0.CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<ConductorScheduleRecord, RbReadyTypeRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_READY_TYPE_ID = ForeignKeys0.CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_READY_TYPE_ID;
    public static final ForeignKey<ConductorScheduleSnapshotRecord, ConductorRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_CONDUCTOR_ID = ForeignKeys0.CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_CONDUCTOR_ID;
    public static final ForeignKey<ConductorScheduleSnapshotRecord, ShiftTypeRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = ForeignKeys0.CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<ConductorScheduleSnapshotRecord, RbReadyTypeRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID = ForeignKeys0.CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID;
    public static final ForeignKey<ConductorSnapshotRecord, RbEmployeeScheduleTypeRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_SCHEDULE_TYPE_ID = ForeignKeys0.CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_SCHEDULE_TYPE_ID;
    public static final ForeignKey<ConductorSnapshotRecord, EmployeeInfoRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_EMPLOYEE_DATA_ID = ForeignKeys0.CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_EMPLOYEE_DATA_ID;
    public static final ForeignKey<ConductorSnapshotRecord, PositionRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_POSITION_ID = ForeignKeys0.CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_POSITION_ID;
    public static final ForeignKey<ConductorSnapshotRecord, RbStateTypeRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_STATE_ID = ForeignKeys0.CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_STATE_ID;
    public static final ForeignKey<DepartureMomentsRecord, DepartureListRecord> DEPARTURE_MOMENTS__FK_DEPARTURE_MOMENTS_TBL_DEPARTURE_LIST_ID = ForeignKeys0.DEPARTURE_MOMENTS__FK_DEPARTURE_MOMENTS_TBL_DEPARTURE_LIST_ID;
    public static final ForeignKey<DriverRecord, EmployeeInfoRecord> DRIVER__FK_DRIVER_TBL_EMPLOYEE_DATA_ID = ForeignKeys0.DRIVER__FK_DRIVER_TBL_EMPLOYEE_DATA_ID;
    public static final ForeignKey<DriverRecord, PositionRecord> DRIVER__FK_DRIVER_TBL_POSITION_ID = ForeignKeys0.DRIVER__FK_DRIVER_TBL_POSITION_ID;
    public static final ForeignKey<DriverRecord, BusRecord> DRIVER__FK_DRIVER_TBL_BUS_ID = ForeignKeys0.DRIVER__FK_DRIVER_TBL_BUS_ID;
    public static final ForeignKey<DriverRecord, DriverGroupRecord> DRIVER__FK_DRIVER_TBL_GROUP_ID = ForeignKeys0.DRIVER__FK_DRIVER_TBL_GROUP_ID;
    public static final ForeignKey<DriverRecord, RbEmployeeScheduleTypeRecord> DRIVER__FK_DRIVER_TBL_SCHEDULE_TYPE = ForeignKeys0.DRIVER__FK_DRIVER_TBL_SCHEDULE_TYPE;
    public static final ForeignKey<DriverRecord, RbStateTypeRecord> DRIVER__FK_DRIVER_TBL_STATE_ID = ForeignKeys0.DRIVER__FK_DRIVER_TBL_STATE_ID;
    public static final ForeignKey<DriverGroupRecord, DriverBrigadeRecord> DRIVER_GROUP__FK_DRIVER_GROUP_TBL_BRIGADE_ID = ForeignKeys0.DRIVER_GROUP__FK_DRIVER_GROUP_TBL_BRIGADE_ID;
    public static final ForeignKey<DriverScheduleRecord, DriverRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_EMPLOYEE_ID_FK = ForeignKeys0.DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_EMPLOYEE_ID_FK;
    public static final ForeignKey<DriverScheduleRecord, ShiftTypeRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_SHIFT_TYPE_ID = ForeignKeys0.DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<DriverScheduleRecord, RbReadyTypeRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_READY_TYPE_ID = ForeignKeys0.DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_READY_TYPE_ID;
    public static final ForeignKey<DriverScheduleSnapshotRecord, DriverRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_EMPLOYEE_ID_FK = ForeignKeys0.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_EMPLOYEE_ID_FK;
    public static final ForeignKey<DriverScheduleSnapshotRecord, ShiftTypeRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = ForeignKeys0.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<DriverScheduleSnapshotRecord, RbReadyTypeRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID = ForeignKeys0.DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID;
    public static final ForeignKey<DriverSnapshotRecord, EmployeeInfoRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_EMPLOYEE_DATA_ID = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_EMPLOYEE_DATA_ID;
    public static final ForeignKey<DriverSnapshotRecord, PositionRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_POSITION_ID = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_POSITION_ID;
    public static final ForeignKey<DriverSnapshotRecord, BusRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_BUS_ID = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_BUS_ID;
    public static final ForeignKey<DriverSnapshotRecord, DriverGroupRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_GROUP_ID = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_GROUP_ID;
    public static final ForeignKey<DriverSnapshotRecord, RbEmployeeScheduleTypeRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_SCHEDULE_TYPE = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_SCHEDULE_TYPE;
    public static final ForeignKey<DriverSnapshotRecord, RbStateTypeRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_STATE_ID = ForeignKeys0.DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_STATE_ID;
    public static final ForeignKey<EmployeeInfoRecord, RbEmployeeTypeRecord> EMPLOYEE_INFO__FK_EMPLOYEE_INFO_EMPLOYEE_TYPE_ID = ForeignKeys0.EMPLOYEE_INFO__FK_EMPLOYEE_INFO_EMPLOYEE_TYPE_ID;
    public static final ForeignKey<FuelCodeRecord, RbFuelTypeRecord> FUEL_CODE__FK_BUS_DATA_TBL_FUEL_TYPE = ForeignKeys0.FUEL_CODE__FK_BUS_DATA_TBL_FUEL_TYPE;
    public static final ForeignKey<IntsidentRecord, RbIntsidentTypeRecord> INTSIDENT__FK_INTSIDENT_TBL_TYPE = ForeignKeys0.INTSIDENT__FK_INTSIDENT_TBL_TYPE;
    public static final ForeignKey<RaceRecord, DriverRecord> RACE__FK_RACE_TBL_DRIVER_ID = ForeignKeys0.RACE__FK_RACE_TBL_DRIVER_ID;
    public static final ForeignKey<RaceRecord, ConductorRecord> RACE__FK_RACE_TBL_CONDUCTOR_ID = ForeignKeys0.RACE__FK_RACE_TBL_CONDUCTOR_ID;
    public static final ForeignKey<RaceRecord, BusRecord> RACE__FK_RACE_TBL_BUS_ID = ForeignKeys0.RACE__FK_RACE_TBL_BUS_ID;
    public static final ForeignKey<RaceRecord, IntsidentRecord> RACE__FK_RACE_TBL_INTSIDENT_ID_FK = ForeignKeys0.RACE__FK_RACE_TBL_INTSIDENT_ID_FK;
    public static final ForeignKey<RaceSnaphotRecord, DriverRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_DRIVER_ID = ForeignKeys0.RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_DRIVER_ID;
    public static final ForeignKey<RaceSnaphotRecord, ConductorRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_CONDUCTOR_ID = ForeignKeys0.RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_CONDUCTOR_ID;
    public static final ForeignKey<RaceSnaphotRecord, BusRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_BUS_ID = ForeignKeys0.RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_BUS_ID;
    public static final ForeignKey<RaceSnaphotRecord, IntsidentRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_INTSIDENT_ID_FK = ForeignKeys0.RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_INTSIDENT_ID_FK;
    public static final ForeignKey<RouteRecord, BusStopListRecord> ROUTE__FK_ROUTE_TBL_BUS_STOP_LIST_ID = ForeignKeys0.ROUTE__FK_ROUTE_TBL_BUS_STOP_LIST_ID;
    public static final ForeignKey<RouteRecord, TrackRecord> ROUTE__FK_ROUTE_TRACK_TBL_ID = ForeignKeys0.ROUTE__FK_ROUTE_TRACK_TBL_ID;
    public static final ForeignKey<RouteScheduleRecord, RouteRecord> ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_ROUTE_ID = ForeignKeys0.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_ROUTE_ID;
    public static final ForeignKey<RouteScheduleRecord, DepartureListRecord> ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = ForeignKeys0.ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID;
    public static final ForeignKey<RouteScheduleSnapshotRecord, RouteRecord> ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_ROUTE_ID = ForeignKeys0.ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_ROUTE_ID;
    public static final ForeignKey<RouteScheduleSnapshotRecord, DepartureListRecord> ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_DEPARTURE_LIST_ID = ForeignKeys0.ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_DEPARTURE_LIST_ID;
    public static final ForeignKey<RouteSnapshotRecord, BusStopListRecord> ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_BUS_STOP_LIST_ID = ForeignKeys0.ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_BUS_STOP_LIST_ID;
    public static final ForeignKey<RouteSnapshotRecord, TrackRecord> ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_TRACK_ID = ForeignKeys0.ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_TRACK_ID;
    public static final ForeignKey<ShiftDepartureMomentsRecord, ShiftDepartureListRecord> SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_SHIFT_ID = ForeignKeys0.SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_SHIFT_ID;
    public static final ForeignKey<ShiftDepartureMomentsRecord, DepartureMomentsRecord> SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_MOMENTS_ID = ForeignKeys0.SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_MOMENTS_ID;
    public static final ForeignKey<ShiftFixedRecord, ShiftScheduleRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_SHIFT_SCHEDULE_ID = ForeignKeys0.SHIFT_FIXED__FK_FIXED_SHIFT_TBL_SHIFT_SCHEDULE_ID;
    public static final ForeignKey<ShiftFixedRecord, DriverRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_DRIVER_ID = ForeignKeys0.SHIFT_FIXED__FK_FIXED_SHIFT_TBL_DRIVER_ID;
    public static final ForeignKey<ShiftFixedRecord, ConductorRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_CONDUCTOR = ForeignKeys0.SHIFT_FIXED__FK_FIXED_SHIFT_TBL_CONDUCTOR;
    public static final ForeignKey<ShiftFixedSnapshotRecord, ShiftScheduleRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_SHIFT_SCHEDULE_ID = ForeignKeys0.SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_SHIFT_SCHEDULE_ID;
    public static final ForeignKey<ShiftFixedSnapshotRecord, DriverRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_DRIVER_ID = ForeignKeys0.SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_DRIVER_ID;
    public static final ForeignKey<ShiftFixedSnapshotRecord, ConductorRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_CONDUCTOR = ForeignKeys0.SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_CONDUCTOR;
    public static final ForeignKey<ShiftScheduleRecord, ShiftTypeRecord> SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_TYPE_ID = ForeignKeys0.SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<ShiftScheduleRecord, ShiftDepartureListRecord> SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_DEPARTURE_LIST_ID = ForeignKeys0.SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_DEPARTURE_LIST_ID;
    public static final ForeignKey<ShiftScheduleSnapshotRecord, ShiftTypeRecord> SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = ForeignKeys0.SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID;
    public static final ForeignKey<ShiftScheduleSnapshotRecord, ShiftDepartureListRecord> SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_DEPARTURE_LIST_ID = ForeignKeys0.SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_DEPARTURE_LIST_ID;
    public static final ForeignKey<TechAvailabilityRecord, BusRecord> TECH_AVAILABILITY__FK__TECH_AVAILABILITY_TBL_BUS_ID = ForeignKeys0.TECH_AVAILABILITY__FK__TECH_AVAILABILITY_TBL_BUS_ID;
    public static final ForeignKey<TechAvailabilityRecord, RbBusConditionTypeRecord> TECH_AVAILABILITY__FK_TECH_AVAILABILITY_TBL_BUS_CONDITION_ID = ForeignKeys0.TECH_AVAILABILITY__FK_TECH_AVAILABILITY_TBL_BUS_CONDITION_ID;
    public static final ForeignKey<TechAvailabilitySnapshotRecord, BusRecord> TECH_AVAILABILITY_SNAPSHOT__FK__TECH_SNAPSHOT_AVAILABILITY_TBL_BUS_ID = ForeignKeys0.TECH_AVAILABILITY_SNAPSHOT__FK__TECH_SNAPSHOT_AVAILABILITY_TBL_BUS_ID;
    public static final ForeignKey<TechAvailabilitySnapshotRecord, RbBusConditionTypeRecord> TECH_AVAILABILITY_SNAPSHOT__FK_TECH_AVAILABILITY_SNAPSHOT_TBL_BUS_CONDITION_ID = ForeignKeys0.TECH_AVAILABILITY_SNAPSHOT__FK_TECH_AVAILABILITY_SNAPSHOT_TBL_BUS_CONDITION_ID;
    public static final ForeignKey<TrackCoordinatesRecord, TrackRecord> TRACK_COORDINATES__FK_TRACK_COORDINATES_TBL_TRACK_ID = ForeignKeys0.TRACK_COORDINATES__FK_TRACK_COORDINATES_TBL_TRACK_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BusRecord, Integer> IDENTITY_BUS = Internal.createIdentity(Bus.BUS, Bus.BUS.ID);
        public static Identity<BusInfoRecord, Short> IDENTITY_BUS_INFO = Internal.createIdentity(BusInfo.BUS_INFO, BusInfo.BUS_INFO.ID);
        public static Identity<BusSnapshotRecord, Integer> IDENTITY_BUS_SNAPSHOT = Internal.createIdentity(BusSnapshot.BUS_SNAPSHOT, BusSnapshot.BUS_SNAPSHOT.ID);
        public static Identity<BusStopListRecord, Integer> IDENTITY_BUS_STOP_LIST = Internal.createIdentity(BusStopList.BUS_STOP_LIST, BusStopList.BUS_STOP_LIST.ID);
        public static Identity<BusStopsRecord, Integer> IDENTITY_BUS_STOPS = Internal.createIdentity(BusStops.BUS_STOPS, BusStops.BUS_STOPS.ID);
        public static Identity<ConductorRecord, Integer> IDENTITY_CONDUCTOR = Internal.createIdentity(Conductor.CONDUCTOR, Conductor.CONDUCTOR.ID);
        public static Identity<ConductorSnapshotRecord, Integer> IDENTITY_CONDUCTOR_SNAPSHOT = Internal.createIdentity(ConductorSnapshot.CONDUCTOR_SNAPSHOT, ConductorSnapshot.CONDUCTOR_SNAPSHOT.ID);
        public static Identity<DepartureListRecord, Integer> IDENTITY_DEPARTURE_LIST = Internal.createIdentity(DepartureList.DEPARTURE_LIST, DepartureList.DEPARTURE_LIST.ID);
        public static Identity<DepartureMomentsRecord, Integer> IDENTITY_DEPARTURE_MOMENTS = Internal.createIdentity(DepartureMoments.DEPARTURE_MOMENTS, DepartureMoments.DEPARTURE_MOMENTS.ID);
        public static Identity<DriverRecord, Integer> IDENTITY_DRIVER = Internal.createIdentity(Driver.DRIVER, Driver.DRIVER.ID);
        public static Identity<DriverBrigadeRecord, Short> IDENTITY_DRIVER_BRIGADE = Internal.createIdentity(DriverBrigade.DRIVER_BRIGADE, DriverBrigade.DRIVER_BRIGADE.ID);
        public static Identity<DriverGroupRecord, Short> IDENTITY_DRIVER_GROUP = Internal.createIdentity(DriverGroup.DRIVER_GROUP, DriverGroup.DRIVER_GROUP.ID);
        public static Identity<DriverSnapshotRecord, Integer> IDENTITY_DRIVER_SNAPSHOT = Internal.createIdentity(DriverSnapshot.DRIVER_SNAPSHOT, DriverSnapshot.DRIVER_SNAPSHOT.ID);
        public static Identity<EmployeeInfoRecord, Short> IDENTITY_EMPLOYEE_INFO = Internal.createIdentity(EmployeeInfo.EMPLOYEE_INFO, EmployeeInfo.EMPLOYEE_INFO.ID);
        public static Identity<FuelCodeRecord, Integer> IDENTITY_FUEL_CODE = Internal.createIdentity(FuelCode.FUEL_CODE, FuelCode.FUEL_CODE.ID);
        public static Identity<IntsidentRecord, Integer> IDENTITY_INTSIDENT = Internal.createIdentity(Intsident.INTSIDENT, Intsident.INTSIDENT.ID);
        public static Identity<PositionRecord, Integer> IDENTITY_POSITION = Internal.createIdentity(Position.POSITION, Position.POSITION.ID);
        public static Identity<RaceRecord, Integer> IDENTITY_RACE = Internal.createIdentity(Race.RACE, Race.RACE.ID);
        public static Identity<RaceSnaphotRecord, Integer> IDENTITY_RACE_SNAPHOT = Internal.createIdentity(RaceSnaphot.RACE_SNAPHOT, RaceSnaphot.RACE_SNAPHOT.ID);
        public static Identity<RbBusConditionTypeRecord, Short> IDENTITY_RB_BUS_CONDITION_TYPE = Internal.createIdentity(RbBusConditionType.RB_BUS_CONDITION_TYPE, RbBusConditionType.RB_BUS_CONDITION_TYPE.ID);
        public static Identity<RbBusMakeRecord, Short> IDENTITY_RB_BUS_MAKE = Internal.createIdentity(RbBusMake.RB_BUS_MAKE, RbBusMake.RB_BUS_MAKE.ID);
        public static Identity<RbBusModelRecord, Short> IDENTITY_RB_BUS_MODEL = Internal.createIdentity(RbBusModel.RB_BUS_MODEL, RbBusModel.RB_BUS_MODEL.ID);
        public static Identity<RbBusStopRecord, Integer> IDENTITY_RB_BUS_STOP = Internal.createIdentity(RbBusStop.RB_BUS_STOP, RbBusStop.RB_BUS_STOP.ID);
        public static Identity<RbEmployeeScheduleTypeRecord, Integer> IDENTITY_RB_EMPLOYEE_SCHEDULE_TYPE = Internal.createIdentity(RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE, RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE.ID);
        public static Identity<RbEmployeeTypeRecord, Integer> IDENTITY_RB_EMPLOYEE_TYPE = Internal.createIdentity(RbEmployeeType.RB_EMPLOYEE_TYPE, RbEmployeeType.RB_EMPLOYEE_TYPE.ID);
        public static Identity<RbFuelTypeRecord, Integer> IDENTITY_RB_FUEL_TYPE = Internal.createIdentity(RbFuelType.RB_FUEL_TYPE, RbFuelType.RB_FUEL_TYPE.ID);
        public static Identity<RbReadyTypeRecord, Integer> IDENTITY_RB_READY_TYPE = Internal.createIdentity(RbReadyType.RB_READY_TYPE, RbReadyType.RB_READY_TYPE.ID);
        public static Identity<RbStateTypeRecord, Short> IDENTITY_RB_STATE_TYPE = Internal.createIdentity(RbStateType.RB_STATE_TYPE, RbStateType.RB_STATE_TYPE.ID);
        public static Identity<RouteRecord, Integer> IDENTITY_ROUTE = Internal.createIdentity(Route.ROUTE, Route.ROUTE.ID);
        public static Identity<ShiftDepartureListRecord, Integer> IDENTITY_SHIFT_DEPARTURE_LIST = Internal.createIdentity(ShiftDepartureList.SHIFT_DEPARTURE_LIST, ShiftDepartureList.SHIFT_DEPARTURE_LIST.ID);
        public static Identity<ShiftDepartureMomentsRecord, Integer> IDENTITY_SHIFT_DEPARTURE_MOMENTS = Internal.createIdentity(ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS, ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS.ID);
        public static Identity<ShiftScheduleRecord, Integer> IDENTITY_SHIFT_SCHEDULE = Internal.createIdentity(ShiftSchedule.SHIFT_SCHEDULE, ShiftSchedule.SHIFT_SCHEDULE.ID);
        public static Identity<ShiftScheduleSnapshotRecord, Integer> IDENTITY_SHIFT_SCHEDULE_SNAPSHOT = Internal.createIdentity(ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT, ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.ID);
        public static Identity<ShiftTypeRecord, Integer> IDENTITY_SHIFT_TYPE = Internal.createIdentity(ShiftType.SHIFT_TYPE, ShiftType.SHIFT_TYPE.ID);
        public static Identity<TrackRecord, Integer> IDENTITY_TRACK = Internal.createIdentity(Track.TRACK, Track.TRACK.ID);
        public static Identity<TrackCoordinatesRecord, Integer> IDENTITY_TRACK_COORDINATES = Internal.createIdentity(TrackCoordinates.TRACK_COORDINATES, TrackCoordinates.TRACK_COORDINATES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BusRecord> PK_BUS_TBL = Internal.createUniqueKey(Bus.BUS, "pk_bus_tbl", Bus.BUS.ID);
        public static final UniqueKey<BusInfoRecord> PK_BUS_INFO_TBL = Internal.createUniqueKey(BusInfo.BUS_INFO, "pk_bus_info_tbl", BusInfo.BUS_INFO.ID);
        public static final UniqueKey<BusInfoRecord> UNIQ_BUS_INFO_TBL_VIN = Internal.createUniqueKey(BusInfo.BUS_INFO, "uniq_bus_info_tbl_vin", BusInfo.BUS_INFO.VIN);
        public static final UniqueKey<BusSnapshotRecord> PK_BUS_SNAPSHOT_TBL = Internal.createUniqueKey(BusSnapshot.BUS_SNAPSHOT, "pk_bus_snapshot_tbl", BusSnapshot.BUS_SNAPSHOT.ID, BusSnapshot.BUS_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<BusStopListRecord> PK_BUS_STOP_LIST_TBL = Internal.createUniqueKey(BusStopList.BUS_STOP_LIST, "pk_bus_stop_list_tbl", BusStopList.BUS_STOP_LIST.ID);
        public static final UniqueKey<BusStopsRecord> PK_BUS_STOPS_TBL = Internal.createUniqueKey(BusStops.BUS_STOPS, "pk_bus_stops_tbl", BusStops.BUS_STOPS.ID);
        public static final UniqueKey<ConductorRecord> PK_CONDUCTOR_TBL_ID = Internal.createUniqueKey(Conductor.CONDUCTOR, "pk_conductor_tbl_id", Conductor.CONDUCTOR.ID);
        public static final UniqueKey<ConductorScheduleRecord> PK_CONDUCTOR_SCHEDULE_TBL = Internal.createUniqueKey(ConductorSchedule.CONDUCTOR_SCHEDULE, "pk_conductor_schedule_tbl", ConductorSchedule.CONDUCTOR_SCHEDULE.CONDUCTOR_ID, ConductorSchedule.CONDUCTOR_SCHEDULE.DATE);
        public static final UniqueKey<ConductorScheduleSnapshotRecord> PK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL = Internal.createUniqueKey(ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT, "pk_conductor_schedule_snapshot_tbl", ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.CONDUCTOR_ID, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.DATE, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<ConductorSnapshotRecord> PK_CONDUCTOR_SNAPSHOT_TBL = Internal.createUniqueKey(ConductorSnapshot.CONDUCTOR_SNAPSHOT, "pk_conductor_snapshot_tbl", ConductorSnapshot.CONDUCTOR_SNAPSHOT.ID, ConductorSnapshot.CONDUCTOR_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<DepartureListRecord> PK_DEPARTURE_LIST_TBL = Internal.createUniqueKey(DepartureList.DEPARTURE_LIST, "pk_departure_list_tbl", DepartureList.DEPARTURE_LIST.ID);
        public static final UniqueKey<DepartureMomentsRecord> PK_DEPARTURE_MOMENTS_TBL = Internal.createUniqueKey(DepartureMoments.DEPARTURE_MOMENTS, "pk_departure_moments_tbl", DepartureMoments.DEPARTURE_MOMENTS.ID);
        public static final UniqueKey<DriverRecord> PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID = Internal.createUniqueKey(Driver.DRIVER, "pk_driver_tbl_employee_snapshot_id", Driver.DRIVER.ID);
        public static final UniqueKey<DriverBrigadeRecord> PK_DRIVER_BRIGADE_TBL = Internal.createUniqueKey(DriverBrigade.DRIVER_BRIGADE, "pk_driver_brigade_tbl", DriverBrigade.DRIVER_BRIGADE.ID);
        public static final UniqueKey<DriverGroupRecord> PK_DRIVER_GROUP_TBL = Internal.createUniqueKey(DriverGroup.DRIVER_GROUP, "pk_driver_group_tbl", DriverGroup.DRIVER_GROUP.ID);
        public static final UniqueKey<DriverScheduleRecord> PK_DRIVER_SCHEDULE_TBL = Internal.createUniqueKey(DriverSchedule.DRIVER_SCHEDULE, "pk_driver_schedule_tbl", DriverSchedule.DRIVER_SCHEDULE.EMPLOYEE_ID, DriverSchedule.DRIVER_SCHEDULE.DATE);
        public static final UniqueKey<DriverScheduleSnapshotRecord> PK_DRIVER_SCHEDULE_SNAPSHOT_TBL = Internal.createUniqueKey(DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT, "pk_driver_schedule_snapshot_tbl", DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.EMPLOYEE_ID, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.DATE, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<DriverSnapshotRecord> PK_EMPLOYEE_SNAPSHOT_TBL = Internal.createUniqueKey(DriverSnapshot.DRIVER_SNAPSHOT, "pk_employee_snapshot_tbl", DriverSnapshot.DRIVER_SNAPSHOT.ID, DriverSnapshot.DRIVER_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<EmployeeInfoRecord> PK_EMPLOYEE_INFO_TBL = Internal.createUniqueKey(EmployeeInfo.EMPLOYEE_INFO, "pk_employee_info_tbl", EmployeeInfo.EMPLOYEE_INFO.ID);
        public static final UniqueKey<FuelCodeRecord> PK_FUEL_CODE_TBL = Internal.createUniqueKey(FuelCode.FUEL_CODE, "pk_fuel_code_tbl", FuelCode.FUEL_CODE.ID);
        public static final UniqueKey<IntsidentRecord> PK_INTSIDENT = Internal.createUniqueKey(Intsident.INTSIDENT, "pk_intsident", Intsident.INTSIDENT.ID);
        public static final UniqueKey<PositionRecord> PK_POSITION_TBL = Internal.createUniqueKey(Position.POSITION, "pk_position_tbl", Position.POSITION.ID);
        public static final UniqueKey<RaceRecord> PK_RACE_TBL = Internal.createUniqueKey(Race.RACE, "pk_race_tbl", Race.RACE.ID);
        public static final UniqueKey<RaceSnaphotRecord> PK_RACE_SNAPHOT_TBL = Internal.createUniqueKey(RaceSnaphot.RACE_SNAPHOT, "pk_race_snaphot_tbl", RaceSnaphot.RACE_SNAPHOT.ID, RaceSnaphot.RACE_SNAPHOT.CREATED_AT);
        public static final UniqueKey<RbBusConditionTypeRecord> PK_BUS_CONDITION_TBL = Internal.createUniqueKey(RbBusConditionType.RB_BUS_CONDITION_TYPE, "pk_bus_condition_tbl", RbBusConditionType.RB_BUS_CONDITION_TYPE.ID);
        public static final UniqueKey<RbBusMakeRecord> PK_RB_BUS_MAKE_TBL = Internal.createUniqueKey(RbBusMake.RB_BUS_MAKE, "pk_rb_bus_make_tbl", RbBusMake.RB_BUS_MAKE.ID);
        public static final UniqueKey<RbBusModelRecord> PK_RB_BUS_MODEL_TBL = Internal.createUniqueKey(RbBusModel.RB_BUS_MODEL, "pk_rb_bus_model_tbl", RbBusModel.RB_BUS_MODEL.ID);
        public static final UniqueKey<RbBusStopRecord> PK_RB_BUS_STOP_TBL = Internal.createUniqueKey(RbBusStop.RB_BUS_STOP, "pk_rb_bus_stop_tbl", RbBusStop.RB_BUS_STOP.ID);
        public static final UniqueKey<RbEmployeeScheduleTypeRecord> PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL = Internal.createUniqueKey(RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE, "pk_rb_employee_schedule_type_tbl", RbEmployeeScheduleType.RB_EMPLOYEE_SCHEDULE_TYPE.ID);
        public static final UniqueKey<RbEmployeeTypeRecord> PK_RB_EMPLOYEE_TYPE_TBL = Internal.createUniqueKey(RbEmployeeType.RB_EMPLOYEE_TYPE, "pk_rb_employee_type_tbl", RbEmployeeType.RB_EMPLOYEE_TYPE.ID);
        public static final UniqueKey<RbFuelTypeRecord> PL_RB_FUEL_TYPE_TBL = Internal.createUniqueKey(RbFuelType.RB_FUEL_TYPE, "pl_rb_fuel_type_tbl", RbFuelType.RB_FUEL_TYPE.ID);
        public static final UniqueKey<RbIntsidentTypeRecord> PK_INTSIDENT_TYPE_TBL = Internal.createUniqueKey(RbIntsidentType.RB_INTSIDENT_TYPE, "pk_intsident_type_tbl", RbIntsidentType.RB_INTSIDENT_TYPE.ID);
        public static final UniqueKey<RbReadyTypeRecord> PK_RB_READY_TYPE_TBL = Internal.createUniqueKey(RbReadyType.RB_READY_TYPE, "pk_rb_ready_type_tbl", RbReadyType.RB_READY_TYPE.ID);
        public static final UniqueKey<RbStateTypeRecord> PK_RB_STATE_TYPE_TBL = Internal.createUniqueKey(RbStateType.RB_STATE_TYPE, "pk_rb_state_type_tbl", RbStateType.RB_STATE_TYPE.ID);
        public static final UniqueKey<RouteRecord> PK_ROUTE_TBL = Internal.createUniqueKey(Route.ROUTE, "pk_route_tbl", Route.ROUTE.ID);
        public static final UniqueKey<RouteScheduleRecord> PK_ROUTE_SCHEDULE_TBL = Internal.createUniqueKey(RouteSchedule.ROUTE_SCHEDULE, "pk_route_schedule_tbl", RouteSchedule.ROUTE_SCHEDULE.ROUTE_ID);
        public static final UniqueKey<RouteScheduleRecord> UNIQ_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = Internal.createUniqueKey(RouteSchedule.ROUTE_SCHEDULE, "uniq_route_schedule_tbl_departure_list_id", RouteSchedule.ROUTE_SCHEDULE.DEPARTURE_LIST_ID);
        public static final UniqueKey<RouteScheduleSnapshotRecord> PK_ROUTE_SCHEDULE_SNAPSHOT_TBL = Internal.createUniqueKey(RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT, "pk_route_schedule_snapshot_tbl", RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.ROUTE_ID, RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<RouteSnapshotRecord> PK_ROUTE_SNAPSOT_TBL = Internal.createUniqueKey(RouteSnapshot.ROUTE_SNAPSHOT, "pk_route_snapsot_tbl", RouteSnapshot.ROUTE_SNAPSHOT.ID, RouteSnapshot.ROUTE_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<ShiftDepartureListRecord> PK_SHIFT_DEPARTURE_LIST_TBL = Internal.createUniqueKey(ShiftDepartureList.SHIFT_DEPARTURE_LIST, "pk_shift_departure_list_tbl", ShiftDepartureList.SHIFT_DEPARTURE_LIST.ID);
        public static final UniqueKey<ShiftDepartureMomentsRecord> PK_SHIFT_DEPARTURE_MOMENTS_TBL = Internal.createUniqueKey(ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS, "pk_shift_departure_moments_tbl", ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS.ID);
        public static final UniqueKey<ShiftFixedRecord> PK_SHIFT_FIXED_TBL = Internal.createUniqueKey(ShiftFixed.SHIFT_FIXED, "pk_shift_fixed_tbl", ShiftFixed.SHIFT_FIXED.SHIFT_SCHEDULE_ID, ShiftFixed.SHIFT_FIXED.DATE);
        public static final UniqueKey<ShiftFixedSnapshotRecord> PK_FIXED_SHIFT_SNAPSHOT_TBL = Internal.createUniqueKey(ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT, "pk_fixed_shift_snapshot_tbl", ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.SHIFT_SCHEDULE_ID, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.DATE, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<ShiftScheduleRecord> PK_SHIFT_SCHEDULE_ID = Internal.createUniqueKey(ShiftSchedule.SHIFT_SCHEDULE, "pk_shift_schedule_id", ShiftSchedule.SHIFT_SCHEDULE.ID);
        public static final UniqueKey<ShiftScheduleSnapshotRecord> PK_SHIFT_SCHEDULE_SNAPSORT_TBL = Internal.createUniqueKey(ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT, "pk_shift_schedule_snapsort_tbl", ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.ID, ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<ShiftTypeRecord> PK_SHIFT_TYPE_TBL = Internal.createUniqueKey(ShiftType.SHIFT_TYPE, "pk_shift_type_tbl", ShiftType.SHIFT_TYPE.ID);
        public static final UniqueKey<TechAvailabilityRecord> PK_TECH_AVAILABILITY_TBL = Internal.createUniqueKey(TechAvailability.TECH_AVAILABILITY, "pk_tech_availability_tbl", TechAvailability.TECH_AVAILABILITY.BUS_ID, TechAvailability.TECH_AVAILABILITY.DATE);
        public static final UniqueKey<TechAvailabilitySnapshotRecord> PK_TECH_SNAPSHOT_AVAILABILITY_TBL = Internal.createUniqueKey(TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT, "pk_tech_snapshot_availability_tbl", TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.BUS_ID, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.DATE, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.CREATED_AT);
        public static final UniqueKey<TrackRecord> PK_TRACK_TBL = Internal.createUniqueKey(Track.TRACK, "pk_track_tbl", Track.TRACK.ID);
        public static final UniqueKey<TrackCoordinatesRecord> PK_TRACK_COORDINATES_TBL = Internal.createUniqueKey(TrackCoordinates.TRACK_COORDINATES, "pk_track_coordinates_tbl", TrackCoordinates.TRACK_COORDINATES.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BusRecord, BusInfoRecord> BUS__FK_BUS_TBL_BUS_INFO_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_INFO_TBL, Bus.BUS, "bus__fk_bus_tbl_bus_info_id", Bus.BUS.BUS_INFO_ID);
        public static final ForeignKey<BusRecord, FuelCodeRecord> BUS__FK_BUS_TBL_FUEL_CODE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_FUEL_CODE_TBL, Bus.BUS, "bus__fk_bus_tbl_fuel_code_id", Bus.BUS.FUEL_CODE_ID);
        public static final ForeignKey<BusRecord, RbBusConditionTypeRecord> BUS__FK_BUS_TBL_CONDITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_CONDITION_TBL, Bus.BUS, "bus__fk_bus_tbl_condition_id", Bus.BUS.CONDITION_ID);
        public static final ForeignKey<BusInfoRecord, RbBusMakeRecord> BUS_INFO__FK_BUS_INFO_TBL_BUS_MAKE = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_BUS_MAKE_TBL, BusInfo.BUS_INFO, "bus_info__fk_bus_info_tbl_bus_make", BusInfo.BUS_INFO.MAKE_ID);
        public static final ForeignKey<BusInfoRecord, RbBusModelRecord> BUS_INFO__FK_BUS_INFO_TBL_BUS_MODEL = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_BUS_MODEL_TBL, BusInfo.BUS_INFO, "bus_info__fk_bus_info_tbl_bus_model", BusInfo.BUS_INFO.MODEL_ID);
        public static final ForeignKey<BusSnapshotRecord, BusInfoRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_INFO_TBL, BusSnapshot.BUS_SNAPSHOT, "bus_snapshot__fk_bus_snapshot_tbl_bus_id", BusSnapshot.BUS_SNAPSHOT.BUS_INFO_ID);
        public static final ForeignKey<BusSnapshotRecord, FuelCodeRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_FUEL_CODE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_FUEL_CODE_TBL, BusSnapshot.BUS_SNAPSHOT, "bus_snapshot__fk_bus_snapshot_tbl_fuel_code_id", BusSnapshot.BUS_SNAPSHOT.FUEL_CODE_ID);
        public static final ForeignKey<BusSnapshotRecord, RbBusConditionTypeRecord> BUS_SNAPSHOT__FK_BUS_SNAPSHOT_TBL_CONDITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_CONDITION_TBL, BusSnapshot.BUS_SNAPSHOT, "bus_snapshot__fk_bus_snapshot_tbl_condition_id", BusSnapshot.BUS_SNAPSHOT.CONDITION_ID);
        public static final ForeignKey<BusStopsRecord, BusStopListRecord> BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_STOP_LIST_TBL, BusStops.BUS_STOPS, "bus_stops__fk_bus_stops_tbl_bus_stop_list_id", BusStops.BUS_STOPS.BUS_STOP_LIST_ID);
        public static final ForeignKey<BusStopsRecord, RbBusStopRecord> BUS_STOPS__FK_BUS_STOPS_TBL_BUS_STOP_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_BUS_STOP_TBL, BusStops.BUS_STOPS, "bus_stops__fk_bus_stops_tbl_bus_stop_id", BusStops.BUS_STOPS.BUS_STOP_ID);
        public static final ForeignKey<ConductorRecord, RbEmployeeScheduleTypeRecord> CONDUCTOR__FK_CONDUCTOR_TBL_SCHEDULE_TYPE_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL, Conductor.CONDUCTOR, "conductor__fk_conductor_tbl_schedule_type_id_fk", Conductor.CONDUCTOR.ID);
        public static final ForeignKey<ConductorRecord, EmployeeInfoRecord> CONDUCTOR__FK_CONDUCTOR_TBL_EMPLOYEE_DATA_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_EMPLOYEE_INFO_TBL, Conductor.CONDUCTOR, "conductor__fk_conductor_tbl_employee_data_id", Conductor.CONDUCTOR.EMPLOYEE_DATA_ID);
        public static final ForeignKey<ConductorRecord, PositionRecord> CONDUCTOR__FK_CONDUCTOR_TBL_POSITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_POSITION_TBL, Conductor.CONDUCTOR, "conductor__fk_conductor_tbl_position_id", Conductor.CONDUCTOR.POSITION_ID);
        public static final ForeignKey<ConductorRecord, RbStateTypeRecord> CONDUCTOR__FK_CONDUCTOR_TBL_STATE_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_STATE_TYPE_TBL, Conductor.CONDUCTOR, "conductor__fk_conductor_tbl_state_id_fk", Conductor.CONDUCTOR.STATE_ID);
        public static final ForeignKey<ConductorScheduleRecord, ConductorRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_CONDUCTOR_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, ConductorSchedule.CONDUCTOR_SCHEDULE, "conductor_schedule__fk_conductor_schedule_tbl_conductor_id", ConductorSchedule.CONDUCTOR_SCHEDULE.CONDUCTOR_ID);
        public static final ForeignKey<ConductorScheduleRecord, ShiftTypeRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, ConductorSchedule.CONDUCTOR_SCHEDULE, "conductor_schedule__fk_conductor_schedule_tbl_shift_type_id", ConductorSchedule.CONDUCTOR_SCHEDULE.SHIFT_TYPE_ID);
        public static final ForeignKey<ConductorScheduleRecord, RbReadyTypeRecord> CONDUCTOR_SCHEDULE__FK_CONDUCTOR_SCHEDULE_TBL_READY_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_READY_TYPE_TBL, ConductorSchedule.CONDUCTOR_SCHEDULE, "conductor_schedule__fk_conductor_schedule_tbl_ready_type_id", ConductorSchedule.CONDUCTOR_SCHEDULE.READY_TYPE_ID);
        public static final ForeignKey<ConductorScheduleSnapshotRecord, ConductorRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_CONDUCTOR_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT, "conductor_schedule_snapshot__fk_conductor_schedule_snapshot_tbl_conductor_id", ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.CONDUCTOR_ID);
        public static final ForeignKey<ConductorScheduleSnapshotRecord, ShiftTypeRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT, "conductor_schedule_snapshot__fk_conductor_schedule_snapshot_tbl_shift_type_id", ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.SHIFT_TYPE_ID);
        public static final ForeignKey<ConductorScheduleSnapshotRecord, RbReadyTypeRecord> CONDUCTOR_SCHEDULE_SNAPSHOT__FK_CONDUCTOR_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_READY_TYPE_TBL, ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT, "conductor_schedule_snapshot__fk_conductor_schedule_snapshot_tbl_ready_type_id", ConductorScheduleSnapshot.CONDUCTOR_SCHEDULE_SNAPSHOT.READY_TYPE_ID);
        public static final ForeignKey<ConductorSnapshotRecord, RbEmployeeScheduleTypeRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_SCHEDULE_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL, ConductorSnapshot.CONDUCTOR_SNAPSHOT, "conductor_snapshot__fk_conductor_snapshot_tbl_schedule_type_id", ConductorSnapshot.CONDUCTOR_SNAPSHOT.ID);
        public static final ForeignKey<ConductorSnapshotRecord, EmployeeInfoRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_EMPLOYEE_DATA_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_EMPLOYEE_INFO_TBL, ConductorSnapshot.CONDUCTOR_SNAPSHOT, "conductor_snapshot__fk_conductor_snapshot_tbl_employee_data_id", ConductorSnapshot.CONDUCTOR_SNAPSHOT.EMPLOYEE_DATA_ID);
        public static final ForeignKey<ConductorSnapshotRecord, PositionRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_POSITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_POSITION_TBL, ConductorSnapshot.CONDUCTOR_SNAPSHOT, "conductor_snapshot__fk_conductor_snapshot_tbl_position_id", ConductorSnapshot.CONDUCTOR_SNAPSHOT.POSITION_ID);
        public static final ForeignKey<ConductorSnapshotRecord, RbStateTypeRecord> CONDUCTOR_SNAPSHOT__FK_CONDUCTOR_SNAPSHOT_TBL_STATE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_STATE_TYPE_TBL, ConductorSnapshot.CONDUCTOR_SNAPSHOT, "conductor_snapshot__fk_conductor_snapshot_tbl_state_id", ConductorSnapshot.CONDUCTOR_SNAPSHOT.STATE_ID);
        public static final ForeignKey<DepartureMomentsRecord, DepartureListRecord> DEPARTURE_MOMENTS__FK_DEPARTURE_MOMENTS_TBL_DEPARTURE_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DEPARTURE_LIST_TBL, DepartureMoments.DEPARTURE_MOMENTS, "departure_moments__fk_departure_moments_tbl_departure_list_id", DepartureMoments.DEPARTURE_MOMENTS.DEPARTURE_LIST_ID);
        public static final ForeignKey<DriverRecord, EmployeeInfoRecord> DRIVER__FK_DRIVER_TBL_EMPLOYEE_DATA_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_EMPLOYEE_INFO_TBL, Driver.DRIVER, "driver__fk_driver_tbl_employee_data_id", Driver.DRIVER.EMPLOYEE_DATA_ID);
        public static final ForeignKey<DriverRecord, PositionRecord> DRIVER__FK_DRIVER_TBL_POSITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_POSITION_TBL, Driver.DRIVER, "driver__fk_driver_tbl_position_id", Driver.DRIVER.POSITION_ID);
        public static final ForeignKey<DriverRecord, BusRecord> DRIVER__FK_DRIVER_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, Driver.DRIVER, "driver__fk_driver_tbl_bus_id", Driver.DRIVER.BUS_ID);
        public static final ForeignKey<DriverRecord, DriverGroupRecord> DRIVER__FK_DRIVER_TBL_GROUP_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_GROUP_TBL, Driver.DRIVER, "driver__fk_driver_tbl_group_id", Driver.DRIVER.GROUP_ID);
        public static final ForeignKey<DriverRecord, RbEmployeeScheduleTypeRecord> DRIVER__FK_DRIVER_TBL_SCHEDULE_TYPE = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL, Driver.DRIVER, "driver__fk_driver_tbl_schedule_type", Driver.DRIVER.SCHEDULE_TYPE);
        public static final ForeignKey<DriverRecord, RbStateTypeRecord> DRIVER__FK_DRIVER_TBL_STATE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_STATE_TYPE_TBL, Driver.DRIVER, "driver__fk_driver_tbl_state_id", Driver.DRIVER.STATE_ID);
        public static final ForeignKey<DriverGroupRecord, DriverBrigadeRecord> DRIVER_GROUP__FK_DRIVER_GROUP_TBL_BRIGADE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_BRIGADE_TBL, DriverGroup.DRIVER_GROUP, "driver_group__fk_driver_group_tbl_brigade_id", DriverGroup.DRIVER_GROUP.BRIGADE_ID);
        public static final ForeignKey<DriverScheduleRecord, DriverRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_EMPLOYEE_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, DriverSchedule.DRIVER_SCHEDULE, "driver_schedule__fk_driver_schedule_tbl_employee_id_fk", DriverSchedule.DRIVER_SCHEDULE.EMPLOYEE_ID);
        public static final ForeignKey<DriverScheduleRecord, ShiftTypeRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, DriverSchedule.DRIVER_SCHEDULE, "driver_schedule__fk_driver_schedule_tbl_shift_type_id", DriverSchedule.DRIVER_SCHEDULE.SCHEDULE_TYPE_ID);
        public static final ForeignKey<DriverScheduleRecord, RbReadyTypeRecord> DRIVER_SCHEDULE__FK_DRIVER_SCHEDULE_TBL_READY_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_READY_TYPE_TBL, DriverSchedule.DRIVER_SCHEDULE, "driver_schedule__fk_driver_schedule_tbl_ready_type_id", DriverSchedule.DRIVER_SCHEDULE.READY_TYPE_ID);
        public static final ForeignKey<DriverScheduleSnapshotRecord, DriverRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_EMPLOYEE_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT, "driver_schedule_snapshot__fk_driver_schedule_snapshot_tbl_employee_id_fk", DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.EMPLOYEE_ID);
        public static final ForeignKey<DriverScheduleSnapshotRecord, ShiftTypeRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT, "driver_schedule_snapshot__fk_driver_schedule_snapshot_tbl_shift_type_id", DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.SHIFT_TYPE_ID);
        public static final ForeignKey<DriverScheduleSnapshotRecord, RbReadyTypeRecord> DRIVER_SCHEDULE_SNAPSHOT__FK_DRIVER_SCHEDULE_SNAPSHOT_TBL_READY_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_READY_TYPE_TBL, DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT, "driver_schedule_snapshot__fk_driver_schedule_snapshot_tbl_ready_type_id", DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.READY_TYPE_ID);
        public static final ForeignKey<DriverSnapshotRecord, EmployeeInfoRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_EMPLOYEE_DATA_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_EMPLOYEE_INFO_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_employee_data_id", DriverSnapshot.DRIVER_SNAPSHOT.EMPLOYEE_DATA_ID);
        public static final ForeignKey<DriverSnapshotRecord, PositionRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_POSITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_POSITION_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_position_id", DriverSnapshot.DRIVER_SNAPSHOT.POSITION_ID);
        public static final ForeignKey<DriverSnapshotRecord, BusRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_bus_id", DriverSnapshot.DRIVER_SNAPSHOT.BUS_ID);
        public static final ForeignKey<DriverSnapshotRecord, DriverGroupRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_GROUP_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_GROUP_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_group_id", DriverSnapshot.DRIVER_SNAPSHOT.GROUP_ID);
        public static final ForeignKey<DriverSnapshotRecord, RbEmployeeScheduleTypeRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_SCHEDULE_TYPE = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_EMPLOYEE_SCHEDULE_TYPE_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_schedule_type", DriverSnapshot.DRIVER_SNAPSHOT.SCHEDULE_TYPE);
        public static final ForeignKey<DriverSnapshotRecord, RbStateTypeRecord> DRIVER_SNAPSHOT__FK_DRIVER_SNAPSHOT_TBL_STATE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_STATE_TYPE_TBL, DriverSnapshot.DRIVER_SNAPSHOT, "driver_snapshot__fk_driver_snapshot_tbl_state_id", DriverSnapshot.DRIVER_SNAPSHOT.STATE_ID);
        public static final ForeignKey<EmployeeInfoRecord, RbEmployeeTypeRecord> EMPLOYEE_INFO__FK_EMPLOYEE_INFO_EMPLOYEE_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_RB_EMPLOYEE_TYPE_TBL, EmployeeInfo.EMPLOYEE_INFO, "employee_info__fk_employee_info_employee_type_id", EmployeeInfo.EMPLOYEE_INFO.EMPLOYEE_TYPE_ID);
        public static final ForeignKey<FuelCodeRecord, RbFuelTypeRecord> FUEL_CODE__FK_BUS_DATA_TBL_FUEL_TYPE = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PL_RB_FUEL_TYPE_TBL, FuelCode.FUEL_CODE, "fuel_code__fk_bus_data_tbl_fuel_type", FuelCode.FUEL_CODE.FUEL_TYPE_ID);
        public static final ForeignKey<IntsidentRecord, RbIntsidentTypeRecord> INTSIDENT__FK_INTSIDENT_TBL_TYPE = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_INTSIDENT_TYPE_TBL, Intsident.INTSIDENT, "intsident__fk_intsident_tbl_type", Intsident.INTSIDENT.TYPE);
        public static final ForeignKey<RaceRecord, DriverRecord> RACE__FK_RACE_TBL_DRIVER_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, Race.RACE, "race__fk_race_tbl_driver_id", Race.RACE.DRIVER_ID);
        public static final ForeignKey<RaceRecord, ConductorRecord> RACE__FK_RACE_TBL_CONDUCTOR_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, Race.RACE, "race__fk_race_tbl_conductor_id", Race.RACE.CONDUCTOR_ID);
        public static final ForeignKey<RaceRecord, BusRecord> RACE__FK_RACE_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, Race.RACE, "race__fk_race_tbl_bus_id", Race.RACE.BUS_ID);
        public static final ForeignKey<RaceRecord, IntsidentRecord> RACE__FK_RACE_TBL_INTSIDENT_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_INTSIDENT, Race.RACE, "race__fk_race_tbl_intsident_id_fk", Race.RACE.INTSIDEND_ID);
        public static final ForeignKey<RaceSnaphotRecord, DriverRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_DRIVER_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, RaceSnaphot.RACE_SNAPHOT, "race_snaphot__fk_race_snaphot_tbl_driver_id", RaceSnaphot.RACE_SNAPHOT.DRIVER_ID);
        public static final ForeignKey<RaceSnaphotRecord, ConductorRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_CONDUCTOR_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, RaceSnaphot.RACE_SNAPHOT, "race_snaphot__fk_race_snaphot_tbl_conductor_id", RaceSnaphot.RACE_SNAPHOT.CONDUCTOR_ID);
        public static final ForeignKey<RaceSnaphotRecord, BusRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, RaceSnaphot.RACE_SNAPHOT, "race_snaphot__fk_race_snaphot_tbl_bus_id", RaceSnaphot.RACE_SNAPHOT.BUS_ID);
        public static final ForeignKey<RaceSnaphotRecord, IntsidentRecord> RACE_SNAPHOT__FK_RACE_SNAPHOT_TBL_INTSIDENT_ID_FK = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_INTSIDENT, RaceSnaphot.RACE_SNAPHOT, "race_snaphot__fk_race_snaphot_tbl_intsident_id_fk", RaceSnaphot.RACE_SNAPHOT.INTSIDEND_ID);
        public static final ForeignKey<RouteRecord, BusStopListRecord> ROUTE__FK_ROUTE_TBL_BUS_STOP_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_STOP_LIST_TBL, Route.ROUTE, "route__fk_route_tbl_bus_stop_list_id", Route.ROUTE.BUS_STOP_LIST_ID);
        public static final ForeignKey<RouteRecord, TrackRecord> ROUTE__FK_ROUTE_TRACK_TBL_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_TRACK_TBL, Route.ROUTE, "route__fk_route_track_tbl_id", Route.ROUTE.TRACK_ID);
        public static final ForeignKey<RouteScheduleRecord, RouteRecord> ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_ROUTE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_ROUTE_TBL, RouteSchedule.ROUTE_SCHEDULE, "route_schedule__fk_route_schedule_tbl_route_id", RouteSchedule.ROUTE_SCHEDULE.ROUTE_ID);
        public static final ForeignKey<RouteScheduleRecord, DepartureListRecord> ROUTE_SCHEDULE__FK_ROUTE_SCHEDULE_TBL_DEPARTURE_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DEPARTURE_LIST_TBL, RouteSchedule.ROUTE_SCHEDULE, "route_schedule__fk_route_schedule_tbl_departure_list_id", RouteSchedule.ROUTE_SCHEDULE.DEPARTURE_LIST_ID);
        public static final ForeignKey<RouteScheduleSnapshotRecord, RouteRecord> ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_ROUTE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_ROUTE_TBL, RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT, "route_schedule_snapshot__fk_route_schedule_snapshot_tbl_route_id", RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.ROUTE_ID);
        public static final ForeignKey<RouteScheduleSnapshotRecord, DepartureListRecord> ROUTE_SCHEDULE_SNAPSHOT__FK_ROUTE_SCHEDULE_SNAPSHOT_TBL_DEPARTURE_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DEPARTURE_LIST_TBL, RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT, "route_schedule_snapshot__fk_route_schedule_snapshot_tbl_departure_list_id", RouteScheduleSnapshot.ROUTE_SCHEDULE_SNAPSHOT.DEPARTURE_LIST_ID);
        public static final ForeignKey<RouteSnapshotRecord, BusStopListRecord> ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_BUS_STOP_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_STOP_LIST_TBL, RouteSnapshot.ROUTE_SNAPSHOT, "route_snapshot__fk_route_snapshot_tbl_bus_stop_list_id", RouteSnapshot.ROUTE_SNAPSHOT.BUS_STOP_LIST_ID);
        public static final ForeignKey<RouteSnapshotRecord, TrackRecord> ROUTE_SNAPSHOT__FK_ROUTE_SNAPSHOT_TBL_TRACK_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_TRACK_TBL, RouteSnapshot.ROUTE_SNAPSHOT, "route_snapshot__fk_route_snapshot_tbl_track_id", RouteSnapshot.ROUTE_SNAPSHOT.TRACK_ID);
        public static final ForeignKey<ShiftDepartureMomentsRecord, ShiftDepartureListRecord> SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_SHIFT_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_DEPARTURE_LIST_TBL, ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS, "shift_departure_moments__fk_shift_departure_moments_tbl_shift_id", ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS.SHIFT_DEPARTURE_LIST_ID);
        public static final ForeignKey<ShiftDepartureMomentsRecord, DepartureMomentsRecord> SHIFT_DEPARTURE_MOMENTS__FK_SHIFT_DEPARTURE_MOMENTS_TBL_MOMENTS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DEPARTURE_MOMENTS_TBL, ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS, "shift_departure_moments__fk_shift_departure_moments_tbl_moments_id", ShiftDepartureMoments.SHIFT_DEPARTURE_MOMENTS.DEPARTURE_MOMENTS_ID);
        public static final ForeignKey<ShiftFixedRecord, ShiftScheduleRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_SHIFT_SCHEDULE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_SCHEDULE_ID, ShiftFixed.SHIFT_FIXED, "shift_fixed__fk_fixed_shift_tbl_shift_schedule_id", ShiftFixed.SHIFT_FIXED.SHIFT_SCHEDULE_ID);
        public static final ForeignKey<ShiftFixedRecord, DriverRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_DRIVER_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, ShiftFixed.SHIFT_FIXED, "shift_fixed__fk_fixed_shift_tbl_driver_id", ShiftFixed.SHIFT_FIXED.DRIVER_ID);
        public static final ForeignKey<ShiftFixedRecord, ConductorRecord> SHIFT_FIXED__FK_FIXED_SHIFT_TBL_CONDUCTOR = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, ShiftFixed.SHIFT_FIXED, "shift_fixed__fk_fixed_shift_tbl_conductor", ShiftFixed.SHIFT_FIXED.CONDUCTOR_ID);
        public static final ForeignKey<ShiftFixedSnapshotRecord, ShiftScheduleRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_SHIFT_SCHEDULE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_SCHEDULE_ID, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT, "shift_fixed_snapshot__fk_fixed_shift_snapshot_tbl_shift_schedule_id", ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.SHIFT_SCHEDULE_ID);
        public static final ForeignKey<ShiftFixedSnapshotRecord, DriverRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_DRIVER_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_DRIVER_TBL_EMPLOYEE_SNAPSHOT_ID, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT, "shift_fixed_snapshot__fk_fixed_shift_snapshot_tbl_driver_id", ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.DRIVER_ID);
        public static final ForeignKey<ShiftFixedSnapshotRecord, ConductorRecord> SHIFT_FIXED_SNAPSHOT__FK_FIXED_SHIFT_SNAPSHOT_TBL_CONDUCTOR = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_CONDUCTOR_TBL_ID, ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT, "shift_fixed_snapshot__fk_fixed_shift_snapshot_tbl_conductor", ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.CONDUCTOR_ID);
        public static final ForeignKey<ShiftScheduleRecord, ShiftTypeRecord> SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, ShiftSchedule.SHIFT_SCHEDULE, "shift_schedule__fk_shift_schedule_tbl_shift_type_id", ShiftSchedule.SHIFT_SCHEDULE.SHIFT_TYPE_ID);
        public static final ForeignKey<ShiftScheduleRecord, ShiftDepartureListRecord> SHIFT_SCHEDULE__FK_SHIFT_SCHEDULE_TBL_SHIFT_DEPARTURE_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_DEPARTURE_LIST_TBL, ShiftSchedule.SHIFT_SCHEDULE, "shift_schedule__fk_shift_schedule_tbl_shift_departure_list_id", ShiftSchedule.SHIFT_SCHEDULE.SHIFT_DEPARTURE_LIST_ID);
        public static final ForeignKey<ShiftScheduleSnapshotRecord, ShiftTypeRecord> SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_TYPE_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_TYPE_TBL, ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT, "shift_schedule_snapshot__fk_shift_schedule_snapshot_tbl_shift_type_id", ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.SHIFT_TYPE_ID);
        public static final ForeignKey<ShiftScheduleSnapshotRecord, ShiftDepartureListRecord> SHIFT_SCHEDULE_SNAPSHOT__FK_SHIFT_SCHEDULE_SNAPSHOT_TBL_SHIFT_DEPARTURE_LIST_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_SHIFT_DEPARTURE_LIST_TBL, ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT, "shift_schedule_snapshot__fk_shift_schedule_snapshot_tbl_shift_departure_list_id", ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.SHIFT_DEPARTURE_LIST_ID);
        public static final ForeignKey<TechAvailabilityRecord, BusRecord> TECH_AVAILABILITY__FK__TECH_AVAILABILITY_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, TechAvailability.TECH_AVAILABILITY, "tech_availability__fk_ tech_availability_tbl_bus_id", TechAvailability.TECH_AVAILABILITY.BUS_ID);
        public static final ForeignKey<TechAvailabilityRecord, RbBusConditionTypeRecord> TECH_AVAILABILITY__FK_TECH_AVAILABILITY_TBL_BUS_CONDITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_CONDITION_TBL, TechAvailability.TECH_AVAILABILITY, "tech_availability__fk_tech_availability_tbl_bus_condition_id", TechAvailability.TECH_AVAILABILITY.BUS_CONDITION_ID);
        public static final ForeignKey<TechAvailabilitySnapshotRecord, BusRecord> TECH_AVAILABILITY_SNAPSHOT__FK__TECH_SNAPSHOT_AVAILABILITY_TBL_BUS_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_TBL, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT, "tech_availability_snapshot__fk_ tech_snapshot_availability_tbl_bus_id", TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.BUS_ID);
        public static final ForeignKey<TechAvailabilitySnapshotRecord, RbBusConditionTypeRecord> TECH_AVAILABILITY_SNAPSHOT__FK_TECH_AVAILABILITY_SNAPSHOT_TBL_BUS_CONDITION_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_BUS_CONDITION_TBL, TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT, "tech_availability_snapshot__fk_tech_availability_snapshot_tbl_bus_condition_id", TechAvailabilitySnapshot.TECH_AVAILABILITY_SNAPSHOT.BUS_CONDITION_ID);
        public static final ForeignKey<TrackCoordinatesRecord, TrackRecord> TRACK_COORDINATES__FK_TRACK_COORDINATES_TBL_TRACK_ID = Internal.createForeignKey(ru.smartsarov.bus.postgres.Keys.PK_TRACK_TBL, TrackCoordinates.TRACK_COORDINATES, "track_coordinates__fk_track_coordinates_tbl_track_id", TrackCoordinates.TRACK_COORDINATES.TRACK_ID);
    }
}
