/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.BusInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusInfoRecord extends UpdatableRecordImpl<BusInfoRecord> implements Record6<Short, String, Short, Short, Short, Short> {

    private static final long serialVersionUID = -358168461;

    /**
     * Setter for <code>public.bus_info.id</code>.
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bus_info.id</code>.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.bus_info.vin</code>.
     */
    public void setVin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bus_info.vin</code>.
     */
    public String getVin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bus_info.year_of_issue</code>.
     */
    public void setYearOfIssue(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bus_info.year_of_issue</code>.
     */
    public Short getYearOfIssue() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.bus_info.make_id</code>.
     */
    public void setMakeId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bus_info.make_id</code>.
     */
    public Short getMakeId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.bus_info.model_id</code>.
     */
    public void setModelId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bus_info.model_id</code>.
     */
    public Short getModelId() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.bus_info.removed</code>.
     */
    public void setRemoved(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bus_info.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Short, String, Short, Short, Short, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Short, String, Short, Short, Short, Short> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return BusInfo.BUS_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BusInfo.BUS_INFO.VIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return BusInfo.BUS_INFO.YEAR_OF_ISSUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return BusInfo.BUS_INFO.MAKE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return BusInfo.BUS_INFO.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return BusInfo.BUS_INFO.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getVin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getYearOfIssue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getMakeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getYearOfIssue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getMakeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value1(Short value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value2(String value) {
        setVin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value3(Short value) {
        setYearOfIssue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value4(Short value) {
        setMakeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value5(Short value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord value6(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusInfoRecord values(Short value1, String value2, Short value3, Short value4, Short value5, Short value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusInfoRecord
     */
    public BusInfoRecord() {
        super(BusInfo.BUS_INFO);
    }

    /**
     * Create a detached, initialised BusInfoRecord
     */
    public BusInfoRecord(Short id, String vin, Short yearOfIssue, Short makeId, Short modelId, Short removed) {
        super(BusInfo.BUS_INFO);

        set(0, id);
        set(1, vin);
        set(2, yearOfIssue);
        set(3, makeId);
        set(4, modelId);
        set(5, removed);
    }
}
