/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.BusStops;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStopsRecord extends UpdatableRecordImpl<BusStopsRecord> implements Record6<Integer, Short, Short, Short, Short, Short> {

    private static final long serialVersionUID = -255656677;

    /**
     * Setter for <code>public.bus_stops.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bus_stops.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bus_stops.bus_stop_list_id</code>.
     */
    public void setBusStopListId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bus_stops.bus_stop_list_id</code>.
     */
    public Short getBusStopListId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.bus_stops.order</code>.
     */
    public void setOrder(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bus_stops.order</code>.
     */
    public Short getOrder() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.bus_stops.bus_stop_id</code>.
     */
    public void setBusStopId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bus_stops.bus_stop_id</code>.
     */
    public Short getBusStopId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.bus_stops.elapsed_time</code>.
     */
    public void setElapsedTime(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bus_stops.elapsed_time</code>.
     */
    public Short getElapsedTime() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.bus_stops.removed</code>.
     */
    public void setRemoved(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bus_stops.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Short, Short, Short, Short, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Short, Short, Short, Short, Short> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BusStops.BUS_STOPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return BusStops.BUS_STOPS.BUS_STOP_LIST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return BusStops.BUS_STOPS.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return BusStops.BUS_STOPS.BUS_STOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return BusStops.BUS_STOPS.ELAPSED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return BusStops.BUS_STOPS.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getBusStopListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getBusStopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getElapsedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getBusStopListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getBusStopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getElapsedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value2(Short value) {
        setBusStopListId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value3(Short value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value4(Short value) {
        setBusStopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value5(Short value) {
        setElapsedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord value6(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStopsRecord values(Integer value1, Short value2, Short value3, Short value4, Short value5, Short value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusStopsRecord
     */
    public BusStopsRecord() {
        super(BusStops.BUS_STOPS);
    }

    /**
     * Create a detached, initialised BusStopsRecord
     */
    public BusStopsRecord(Integer id, Short busStopListId, Short order, Short busStopId, Short elapsedTime, Short removed) {
        super(BusStops.BUS_STOPS);

        set(0, id);
        set(1, busStopListId);
        set(2, order);
        set(3, busStopId);
        set(4, elapsedTime);
        set(5, removed);
    }
}
