/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.sql.Date;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.DriverScheduleSnapshot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverScheduleSnapshotRecord extends UpdatableRecordImpl<DriverScheduleSnapshotRecord> implements Record6<Short, Date, Short, OffsetDateTime, OffsetDateTime, Short> {

    private static final long serialVersionUID = -432529665;

    /**
     * Setter for <code>public.driver_schedule_snapshot.employee_id</code>.
     */
    public void setEmployeeId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.employee_id</code>.
     */
    public Short getEmployeeId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.driver_schedule_snapshot.date</code>.
     */
    public void setDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.driver_schedule_snapshot.shift_type_id</code>.
     */
    public void setShiftTypeId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.shift_type_id</code>.
     */
    public Short getShiftTypeId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.driver_schedule_snapshot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.driver_schedule_snapshot.ended_at</code>.
     */
    public void setEndedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.driver_schedule_snapshot.removed</code>.
     */
    public void setRemoved(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.driver_schedule_snapshot.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Short, Date, OffsetDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Short, Date, Short, OffsetDateTime, OffsetDateTime, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Short, Date, Short, OffsetDateTime, OffsetDateTime, Short> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.EMPLOYEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.SHIFT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field4() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.ENDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component1() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value1(Short value) {
        setEmployeeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value2(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value3(Short value) {
        setShiftTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value5(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord value6(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverScheduleSnapshotRecord values(Short value1, Date value2, Short value3, OffsetDateTime value4, OffsetDateTime value5, Short value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DriverScheduleSnapshotRecord
     */
    public DriverScheduleSnapshotRecord() {
        super(DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT);
    }

    /**
     * Create a detached, initialised DriverScheduleSnapshotRecord
     */
    public DriverScheduleSnapshotRecord(Short employeeId, Date date, Short shiftTypeId, OffsetDateTime createdAt, OffsetDateTime endedAt, Short removed) {
        super(DriverScheduleSnapshot.DRIVER_SCHEDULE_SNAPSHOT);

        set(0, employeeId);
        set(1, date);
        set(2, shiftTypeId);
        set(3, createdAt);
        set(4, endedAt);
        set(5, removed);
    }
}
