/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Record2;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.DriverSnapshot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverSnapshotRecord extends UpdatableRecordImpl<DriverSnapshotRecord> implements Record12<Integer, Short, Short, Short, Boolean, Short, Short, Short, Boolean, OffsetDateTime, OffsetDateTime, Short> {

    private static final long serialVersionUID = 2055899287;

    /**
     * Setter for <code>public.driver_snapshot.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.driver_snapshot.employee_data_id</code>.
     */
    public void setEmployeeDataId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.employee_data_id</code>.
     */
    public Short getEmployeeDataId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.driver_snapshot.position_id</code>.
     */
    public void setPositionId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.position_id</code>.
     */
    public Short getPositionId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.driver_snapshot.bus_id</code>.
     */
    public void setBusId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.bus_id</code>.
     */
    public Short getBusId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.driver_snapshot.brigadier_flag</code>.
     */
    public void setBrigadierFlag(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.brigadier_flag</code>.
     */
    public Boolean getBrigadierFlag() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.driver_snapshot.group_id</code>.
     */
    public void setGroupId(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.group_id</code>.
     */
    public Short getGroupId() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.driver_snapshot.schedule_type</code>.
     */
    public void setScheduleType(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.schedule_type</code>.
     */
    public Short getScheduleType() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.driver_snapshot.state_id</code>.
     */
    public void setStateId(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.state_id</code>.
     */
    public Short getStateId() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.driver_snapshot.ticket_flag</code>.
     */
    public void setTicketFlag(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.ticket_flag</code>.
     */
    public Boolean getTicketFlag() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.driver_snapshot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.driver_snapshot.ended_at</code>.
     */
    public void setEndedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.driver_snapshot.removed</code>.
     */
    public void setRemoved(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.driver_snapshot.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, OffsetDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Short, Short, Short, Boolean, Short, Short, Short, Boolean, OffsetDateTime, OffsetDateTime, Short> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Short, Short, Short, Boolean, Short, Short, Short, Boolean, OffsetDateTime, OffsetDateTime, Short> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DriverSnapshot.DRIVER_SNAPSHOT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return DriverSnapshot.DRIVER_SNAPSHOT.EMPLOYEE_DATA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return DriverSnapshot.DRIVER_SNAPSHOT.POSITION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return DriverSnapshot.DRIVER_SNAPSHOT.BUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return DriverSnapshot.DRIVER_SNAPSHOT.BRIGADIER_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return DriverSnapshot.DRIVER_SNAPSHOT.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return DriverSnapshot.DRIVER_SNAPSHOT.SCHEDULE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return DriverSnapshot.DRIVER_SNAPSHOT.STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return DriverSnapshot.DRIVER_SNAPSHOT.TICKET_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field10() {
        return DriverSnapshot.DRIVER_SNAPSHOT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field11() {
        return DriverSnapshot.DRIVER_SNAPSHOT.ENDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field12() {
        return DriverSnapshot.DRIVER_SNAPSHOT.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getEmployeeDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getPositionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getBrigadierFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getScheduleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getTicketFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component11() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component12() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getEmployeeDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getPositionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getBrigadierFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getScheduleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getTicketFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value11() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value12() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value2(Short value) {
        setEmployeeDataId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value3(Short value) {
        setPositionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value4(Short value) {
        setBusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value5(Boolean value) {
        setBrigadierFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value6(Short value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value7(Short value) {
        setScheduleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value8(Short value) {
        setStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value9(Boolean value) {
        setTicketFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value10(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value11(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord value12(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DriverSnapshotRecord values(Integer value1, Short value2, Short value3, Short value4, Boolean value5, Short value6, Short value7, Short value8, Boolean value9, OffsetDateTime value10, OffsetDateTime value11, Short value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DriverSnapshotRecord
     */
    public DriverSnapshotRecord() {
        super(DriverSnapshot.DRIVER_SNAPSHOT);
    }

    /**
     * Create a detached, initialised DriverSnapshotRecord
     */
    public DriverSnapshotRecord(Integer id, Short employeeDataId, Short positionId, Short busId, Boolean brigadierFlag, Short groupId, Short scheduleType, Short stateId, Boolean ticketFlag, OffsetDateTime createdAt, OffsetDateTime endedAt, Short removed) {
        super(DriverSnapshot.DRIVER_SNAPSHOT);

        set(0, id);
        set(1, employeeDataId);
        set(2, positionId);
        set(3, busId);
        set(4, brigadierFlag);
        set(5, groupId);
        set(6, scheduleType);
        set(7, stateId);
        set(8, ticketFlag);
        set(9, createdAt);
        set(10, endedAt);
        set(11, removed);
    }
}
