/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.RaceSnaphot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceSnaphotRecord extends UpdatableRecordImpl<RaceSnaphotRecord> implements Record10<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, OffsetDateTime, OffsetDateTime, Short> {

    private static final long serialVersionUID = 1359753947;

    /**
     * Setter for <code>public.race_snaphot.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.race_snaphot.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.race_snaphot.driver_id</code>.
     */
    public void setDriverId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.race_snaphot.driver_id</code>.
     */
    public Short getDriverId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.race_snaphot.conductor_id</code>.
     */
    public void setConductorId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.race_snaphot.conductor_id</code>.
     */
    public Short getConductorId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.race_snaphot.bus_id</code>.
     */
    public void setBusId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.race_snaphot.bus_id</code>.
     */
    public Short getBusId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.race_snaphot.ts_start</code>.
     */
    public void setTsStart(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.race_snaphot.ts_start</code>.
     */
    public OffsetDateTime getTsStart() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.race_snaphot.done</code>.
     */
    public void setDone(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.race_snaphot.done</code>.
     */
    public Boolean getDone() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.race_snaphot.intsidend_id</code>.
     */
    public void setIntsidendId(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.race_snaphot.intsidend_id</code>.
     */
    public Short getIntsidendId() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.race_snaphot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.race_snaphot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.race_snaphot.ended_at</code>.
     */
    public void setEndedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.race_snaphot.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.race_snaphot.removed</code>.
     */
    public void setRemoved(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.race_snaphot.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, OffsetDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, OffsetDateTime, OffsetDateTime, Short> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, OffsetDateTime, OffsetDateTime, Short> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RaceSnaphot.RACE_SNAPHOT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return RaceSnaphot.RACE_SNAPHOT.DRIVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return RaceSnaphot.RACE_SNAPHOT.CONDUCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return RaceSnaphot.RACE_SNAPHOT.BUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return RaceSnaphot.RACE_SNAPHOT.TS_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return RaceSnaphot.RACE_SNAPHOT.DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return RaceSnaphot.RACE_SNAPHOT.INTSIDEND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return RaceSnaphot.RACE_SNAPHOT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field9() {
        return RaceSnaphot.RACE_SNAPHOT.ENDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field10() {
        return RaceSnaphot.RACE_SNAPHOT.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getTsStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getIntsidendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component9() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component10() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getTsStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getIntsidendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value9() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value10() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value2(Short value) {
        setDriverId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value3(Short value) {
        setConductorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value4(Short value) {
        setBusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value5(OffsetDateTime value) {
        setTsStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value6(Boolean value) {
        setDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value7(Short value) {
        setIntsidendId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value8(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value9(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord value10(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceSnaphotRecord values(Integer value1, Short value2, Short value3, Short value4, OffsetDateTime value5, Boolean value6, Short value7, OffsetDateTime value8, OffsetDateTime value9, Short value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceSnaphotRecord
     */
    public RaceSnaphotRecord() {
        super(RaceSnaphot.RACE_SNAPHOT);
    }

    /**
     * Create a detached, initialised RaceSnaphotRecord
     */
    public RaceSnaphotRecord(Integer id, Short driverId, Short conductorId, Short busId, OffsetDateTime tsStart, Boolean done, Short intsidendId, OffsetDateTime createdAt, OffsetDateTime endedAt, Short removed) {
        super(RaceSnaphot.RACE_SNAPHOT);

        set(0, id);
        set(1, driverId);
        set(2, conductorId);
        set(3, busId);
        set(4, tsStart);
        set(5, done);
        set(6, intsidendId);
        set(7, createdAt);
        set(8, endedAt);
        set(9, removed);
    }
}
