/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.Race;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceRecord extends UpdatableRecordImpl<RaceRecord> implements Record8<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, Short> {

    private static final long serialVersionUID = 58380147;

    /**
     * Setter for <code>public.race.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.race.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.race.driver_id</code>.
     */
    public void setDriverId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.race.driver_id</code>.
     */
    public Short getDriverId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.race.conductor_id</code>.
     */
    public void setConductorId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.race.conductor_id</code>.
     */
    public Short getConductorId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.race.bus_id</code>.
     */
    public void setBusId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.race.bus_id</code>.
     */
    public Short getBusId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.race.ts_start</code>.
     */
    public void setTsStart(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.race.ts_start</code>.
     */
    public OffsetDateTime getTsStart() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.race.done</code>.
     */
    public void setDone(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.race.done</code>.
     */
    public Boolean getDone() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.race.incidend_id</code>.
     */
    public void setIncidendId(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.race.incidend_id</code>.
     */
    public Short getIncidendId() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.race.removed</code>.
     */
    public void setRemoved(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.race.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, Short> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Short, Short, Short, OffsetDateTime, Boolean, Short, Short> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Race.RACE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return Race.RACE.DRIVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return Race.RACE.CONDUCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return Race.RACE.BUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return Race.RACE.TS_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Race.RACE.DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return Race.RACE.INCIDEND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Race.RACE.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getTsStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getIncidendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getBusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getTsStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getIncidendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value2(Short value) {
        setDriverId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value3(Short value) {
        setConductorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value4(Short value) {
        setBusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value5(OffsetDateTime value) {
        setTsStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value6(Boolean value) {
        setDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value7(Short value) {
        setIncidendId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord value8(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceRecord values(Integer value1, Short value2, Short value3, Short value4, OffsetDateTime value5, Boolean value6, Short value7, Short value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceRecord
     */
    public RaceRecord() {
        super(Race.RACE);
    }

    /**
     * Create a detached, initialised RaceRecord
     */
    public RaceRecord(Integer id, Short driverId, Short conductorId, Short busId, OffsetDateTime tsStart, Boolean done, Short incidendId, Short removed) {
        super(Race.RACE);

        set(0, id);
        set(1, driverId);
        set(2, conductorId);
        set(3, busId);
        set(4, tsStart);
        set(5, done);
        set(6, incidendId);
        set(7, removed);
    }
}
