/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.RbBusStop;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RbBusStopRecord extends UpdatableRecordImpl<RbBusStopRecord> implements Record5<Integer, String, BigDecimal, BigDecimal, Short> {

    private static final long serialVersionUID = 1163191571;

    /**
     * Setter for <code>public.rb_bus_stop.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rb_bus_stop.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.rb_bus_stop.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rb_bus_stop.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rb_bus_stop.lon</code>.
     */
    public void setLon(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rb_bus_stop.lon</code>.
     */
    public BigDecimal getLon() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.rb_bus_stop.lat</code>.
     */
    public void setLat(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rb_bus_stop.lat</code>.
     */
    public BigDecimal getLat() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.rb_bus_stop.removed</code>.
     */
    public void setRemoved(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rb_bus_stop.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, BigDecimal, BigDecimal, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, BigDecimal, BigDecimal, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RbBusStop.RB_BUS_STOP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RbBusStop.RB_BUS_STOP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return RbBusStop.RB_BUS_STOP.LON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return RbBusStop.RB_BUS_STOP.LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return RbBusStop.RB_BUS_STOP.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord value3(BigDecimal value) {
        setLon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord value4(BigDecimal value) {
        setLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord value5(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RbBusStopRecord values(Integer value1, String value2, BigDecimal value3, BigDecimal value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RbBusStopRecord
     */
    public RbBusStopRecord() {
        super(RbBusStop.RB_BUS_STOP);
    }

    /**
     * Create a detached, initialised RbBusStopRecord
     */
    public RbBusStopRecord(Integer id, String name, BigDecimal lon, BigDecimal lat, Short removed) {
        super(RbBusStop.RB_BUS_STOP);

        set(0, id);
        set(1, name);
        set(2, lon);
        set(3, lat);
        set(4, removed);
    }
}
