/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.ShiftSchedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShiftScheduleRecord extends UpdatableRecordImpl<ShiftScheduleRecord> implements Record8<Integer, String, Short, Short, Boolean, Boolean, Boolean, Short> {

    private static final long serialVersionUID = -588317016;

    /**
     * Setter for <code>public.shift_schedule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shift_schedule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shift_schedule.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shift_schedule.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shift_schedule.shift_type_id</code>.
     */
    public void setShiftTypeId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shift_schedule.shift_type_id</code>.
     */
    public Short getShiftTypeId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.shift_schedule.shift_departure_list_id</code>.
     */
    public void setShiftDepartureListId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shift_schedule.shift_departure_list_id</code>.
     */
    public Short getShiftDepartureListId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.shift_schedule.from_garage_before_flag</code>.
     */
    public void setFromGarageBeforeFlag(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shift_schedule.from_garage_before_flag</code>.
     */
    public Boolean getFromGarageBeforeFlag() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.shift_schedule.to_garage_after_flag</code>.
     */
    public void setToGarageAfterFlag(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shift_schedule.to_garage_after_flag</code>.
     */
    public Boolean getToGarageAfterFlag() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.shift_schedule.garage_between_flag</code>.
     */
    public void setGarageBetweenFlag(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shift_schedule.garage_between_flag</code>.
     */
    public Boolean getGarageBetweenFlag() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.shift_schedule.removed</code>.
     */
    public void setRemoved(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shift_schedule.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Short, Short, Boolean, Boolean, Boolean, Short> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Short, Short, Boolean, Boolean, Boolean, Short> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ShiftSchedule.SHIFT_SCHEDULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ShiftSchedule.SHIFT_SCHEDULE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return ShiftSchedule.SHIFT_SCHEDULE.SHIFT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return ShiftSchedule.SHIFT_SCHEDULE.SHIFT_DEPARTURE_LIST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return ShiftSchedule.SHIFT_SCHEDULE.FROM_GARAGE_BEFORE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return ShiftSchedule.SHIFT_SCHEDULE.TO_GARAGE_AFTER_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return ShiftSchedule.SHIFT_SCHEDULE.GARAGE_BETWEEN_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return ShiftSchedule.SHIFT_SCHEDULE.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getShiftDepartureListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getFromGarageBeforeFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getToGarageAfterFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getGarageBetweenFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getShiftDepartureListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getFromGarageBeforeFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getToGarageAfterFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getGarageBetweenFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value3(Short value) {
        setShiftTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value4(Short value) {
        setShiftDepartureListId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value5(Boolean value) {
        setFromGarageBeforeFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value6(Boolean value) {
        setToGarageAfterFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value7(Boolean value) {
        setGarageBetweenFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord value8(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleRecord values(Integer value1, String value2, Short value3, Short value4, Boolean value5, Boolean value6, Boolean value7, Short value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShiftScheduleRecord
     */
    public ShiftScheduleRecord() {
        super(ShiftSchedule.SHIFT_SCHEDULE);
    }

    /**
     * Create a detached, initialised ShiftScheduleRecord
     */
    public ShiftScheduleRecord(Integer id, String name, Short shiftTypeId, Short shiftDepartureListId, Boolean fromGarageBeforeFlag, Boolean toGarageAfterFlag, Boolean garageBetweenFlag, Short removed) {
        super(ShiftSchedule.SHIFT_SCHEDULE);

        set(0, id);
        set(1, name);
        set(2, shiftTypeId);
        set(3, shiftDepartureListId);
        set(4, fromGarageBeforeFlag);
        set(5, toGarageAfterFlag);
        set(6, garageBetweenFlag);
        set(7, removed);
    }
}
