/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.sql.Date;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.ShiftFixedSnapshot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShiftFixedSnapshotRecord extends UpdatableRecordImpl<ShiftFixedSnapshotRecord> implements Record7<Integer, Date, Integer, Integer, OffsetDateTime, OffsetDateTime, Short> {

    private static final long serialVersionUID = 1384932541;

    /**
     * Setter for <code>public.shift_fixed_snapshot.shift_schedule_id</code>.
     */
    public void setShiftScheduleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.shift_schedule_id</code>.
     */
    public Integer getShiftScheduleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.date</code>.
     */
    public void setDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.driver_id</code>.
     */
    public void setDriverId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.driver_id</code>.
     */
    public Integer getDriverId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.conductor_id</code>.
     */
    public void setConductorId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.conductor_id</code>.
     */
    public Integer getConductorId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.ended_at</code>.
     */
    public void setEndedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.shift_fixed_snapshot.removed</code>.
     */
    public void setRemoved(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shift_fixed_snapshot.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Date, OffsetDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Integer, OffsetDateTime, OffsetDateTime, Short> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Integer, OffsetDateTime, OffsetDateTime, Short> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.SHIFT_SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.DRIVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.CONDUCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.ENDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getShiftScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getShiftScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDriverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getConductorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value1(Integer value) {
        setShiftScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value2(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value3(Integer value) {
        setDriverId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value4(Integer value) {
        setConductorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value6(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord value7(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftFixedSnapshotRecord values(Integer value1, Date value2, Integer value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6, Short value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShiftFixedSnapshotRecord
     */
    public ShiftFixedSnapshotRecord() {
        super(ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT);
    }

    /**
     * Create a detached, initialised ShiftFixedSnapshotRecord
     */
    public ShiftFixedSnapshotRecord(Integer shiftScheduleId, Date date, Integer driverId, Integer conductorId, OffsetDateTime createdAt, OffsetDateTime endedAt, Short removed) {
        super(ShiftFixedSnapshot.SHIFT_FIXED_SNAPSHOT);

        set(0, shiftScheduleId);
        set(1, date);
        set(2, driverId);
        set(3, conductorId);
        set(4, createdAt);
        set(5, endedAt);
        set(6, removed);
    }
}
