/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.bus.postgres.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.bus.postgres.tables.ShiftScheduleSnapshot;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShiftScheduleSnapshotRecord extends UpdatableRecordImpl<ShiftScheduleSnapshotRecord> implements Record10<Integer, String, Short, Short, Boolean, Boolean, Boolean, OffsetDateTime, OffsetDateTime, Short> {

    private static final long serialVersionUID = 54860251;

    /**
     * Setter for <code>public.shift_schedule_snapshot.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.shift_type_id</code>.
     */
    public void setShiftTypeId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.shift_type_id</code>.
     */
    public Short getShiftTypeId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.shift_departure_list_id</code>.
     */
    public void setShiftDepartureListId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.shift_departure_list_id</code>.
     */
    public Short getShiftDepartureListId() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.from_garage_before_flag</code>.
     */
    public void setFromGarageBeforeFlag(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.from_garage_before_flag</code>.
     */
    public Boolean getFromGarageBeforeFlag() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.to_garage_after_flag</code>.
     */
    public void setToGarageAfterFlag(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.to_garage_after_flag</code>.
     */
    public Boolean getToGarageAfterFlag() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.garage_between_flag</code>.
     */
    public void setGarageBetweenFlag(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.garage_between_flag</code>.
     */
    public Boolean getGarageBetweenFlag() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.ended_at</code>.
     */
    public void setEndedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.shift_schedule_snapshot.removed</code>.
     */
    public void setRemoved(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.shift_schedule_snapshot.removed</code>.
     */
    public Short getRemoved() {
        return (Short) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, OffsetDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Short, Short, Boolean, Boolean, Boolean, OffsetDateTime, OffsetDateTime, Short> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Short, Short, Boolean, Boolean, Boolean, OffsetDateTime, OffsetDateTime, Short> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.SHIFT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.SHIFT_DEPARTURE_LIST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.FROM_GARAGE_BEFORE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.TO_GARAGE_AFTER_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.GARAGE_BETWEEN_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field9() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.ENDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field10() {
        return ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT.REMOVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getShiftDepartureListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getFromGarageBeforeFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getToGarageAfterFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getGarageBetweenFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component9() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component10() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getShiftTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getShiftDepartureListId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getFromGarageBeforeFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getToGarageAfterFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getGarageBetweenFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value9() {
        return getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value10() {
        return getRemoved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value3(Short value) {
        setShiftTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value4(Short value) {
        setShiftDepartureListId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value5(Boolean value) {
        setFromGarageBeforeFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value6(Boolean value) {
        setToGarageAfterFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value7(Boolean value) {
        setGarageBetweenFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value8(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value9(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord value10(Short value) {
        setRemoved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShiftScheduleSnapshotRecord values(Integer value1, String value2, Short value3, Short value4, Boolean value5, Boolean value6, Boolean value7, OffsetDateTime value8, OffsetDateTime value9, Short value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShiftScheduleSnapshotRecord
     */
    public ShiftScheduleSnapshotRecord() {
        super(ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT);
    }

    /**
     * Create a detached, initialised ShiftScheduleSnapshotRecord
     */
    public ShiftScheduleSnapshotRecord(Integer id, String name, Short shiftTypeId, Short shiftDepartureListId, Boolean fromGarageBeforeFlag, Boolean toGarageAfterFlag, Boolean garageBetweenFlag, OffsetDateTime createdAt, OffsetDateTime endedAt, Short removed) {
        super(ShiftScheduleSnapshot.SHIFT_SCHEDULE_SNAPSHOT);

        set(0, id);
        set(1, name);
        set(2, shiftTypeId);
        set(3, shiftDepartureListId);
        set(4, fromGarageBeforeFlag);
        set(5, toGarageAfterFlag);
        set(6, garageBetweenFlag);
        set(7, createdAt);
        set(8, endedAt);
        set(9, removed);
    }
}
